// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// APIResource specifies the name of a resource and whether it is namespaced.
type APIResource struct {
	// Categories is a list of the grouped resources this resource belongs to (e.g. 'all')
	Categories *[]string `json:"categories,omitempty" yaml:"categories,omitempty"`

	// Group is the preferred group of the resource.  Empty implies the group of the containing resource list. For subresources, this may have a different value, for example: Scale".
	Group *string `json:"group,omitempty" yaml:"group,omitempty"`

	// Kind is the kind for the resource (e.g. 'Foo' is the kind for a resource 'foo')
	Kind string `json:"kind" yaml:"kind"`

	// Name is the plural name of the resource.
	Name string `json:"name" yaml:"name"`

	// Namespaced indicates if a resource is namespaced or not.
	Namespaced bool `json:"namespaced" yaml:"namespaced"`

	// ShortNames is a list of suggested short names of the resource.
	ShortNames *[]string `json:"shortNames,omitempty" yaml:"shortNames,omitempty"`

	// SingularName is the singular name of the resource.  This allows clients to handle plural and singular opaquely. The singularName is more correct for reporting status on a single item and both singular and plural are allowed from the kubectl CLI interface.
	SingularName string `json:"singularName" yaml:"singularName"`

	// The hash value of the storage version, the version this resource is converted to when written to the data store. Value must be treated as opaque by clients. Only equality comparison on the value is valid. This is an alpha feature and may change or be removed in the future. The field is populated by the apiserver only if the StorageVersionHash feature gate is enabled. This field will remain optional even if it graduates.
	StorageVersionHash *string `json:"storageVersionHash,omitempty" yaml:"storageVersionHash,omitempty"`

	// Verbs is a list of supported kube verbs (this includes get, list, watch, create, update, patch, delete, deletecollection, and proxy)
	Verbs []string `json:"verbs" yaml:"verbs"`

	// Version is the preferred version of the resource.  Empty implies the version of the containing resource list For subresources, this may have a different value, for example: v1 (while inside a v1beta1 version of the core resource's group)".
	Version *string `json:"version,omitempty" yaml:"version,omitempty"`
}

func NewAPIResource() *APIResource {
	return &APIResource{}
}

func NewAPIResourceWithSpec(spec *APIResource) *APIResource {
	
	return spec
}

func RegisterAPIResource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[APIResource]()).JsNamespace("k8s.apimachinery.meta.v1").Fields(
		js.Field("Categories"),
		js.Field("Group"),
		js.Field("Kind"),
		js.Field("Name"),
		js.Field("Namespaced"),
		js.Field("ShortNames"),
		js.Field("SingularName"),
		js.Field("StorageVersionHash"),
		js.Field("Verbs"),
		js.Field("Version"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewAPIResource)),
		js.Constructor(reflect.ValueOf(NewAPIResourceWithSpec)),
	)
}