// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// APIVersions lists the versions that are available, to allow clients to discover the API at /api, which is the root path of the legacy v1 API.
type APIVersions struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty" yaml:"apiVersion,omitempty"`

	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`

	// A map of client CIDR to server address that is serving this group. This is to help clients reach servers in the most network-efficient way possible. Clients can use the appropriate server address as per the CIDR that they match. In case of multiple matches, clients should use the longest matching CIDR. The server returns only those CIDRs that it thinks that the client can match. For example: the master will return an internal IP CIDR only, if the client reaches the server using an internal IP. Server looks at X-Forwarded-For header or X-Real-Ip header or request.RemoteAddr (in that order) to get the client IP.
	ServerAddressByClientCIDRs []*ServerAddressByClientCIDR `json:"serverAddressByClientCIDRs" yaml:"serverAddressByClientCIDRs"`

	// Versions are the api versions that are available.
	Versions []string `json:"versions" yaml:"versions"`
}

func NewAPIVersions() *APIVersions {
	return &APIVersions{}
}

func NewAPIVersionsWithSpec(spec *APIVersions) *APIVersions {
	version := "v1"
	kind := "APIVersions"
	
	spec.ApiVersion = &version
	spec.Kind = &kind
	return spec
}

func RegisterAPIVersions(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[APIVersions]()).JsNamespace("k8s.apimachinery.meta.v1").Fields(
		js.Field("ApiVersion"),
		js.Field("Kind"),
		js.Field("ServerAddressByClientCIDRs"),
		js.Field("Versions"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewAPIVersions)),
		js.Constructor(reflect.ValueOf(NewAPIVersionsWithSpec)),
	)
}