// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
type LabelSelector struct {
	// MatchExpressions is a list of label selector requirements. The requirements are ANDed.
	MatchExpressions []*LabelSelectorRequirement `json:"matchExpressions,omitempty" yaml:"matchExpressions,omitempty"`

	// MatchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
	MatchLabels map[string]string `json:"matchLabels,omitempty" yaml:"matchLabels,omitempty"`
}

func NewLabelSelector() *LabelSelector {
	return &LabelSelector{}
}

func NewLabelSelectorWithSpec(spec *LabelSelector) *LabelSelector {
	
	return spec
}

func RegisterLabelSelector(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[LabelSelector]()).JsNamespace("k8s.apimachinery.meta.v1").Fields(
		js.Field("MatchExpressions"),
		js.Field("MatchLabels"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewLabelSelector)),
		js.Constructor(reflect.ValueOf(NewLabelSelectorWithSpec)),
	)
}