// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// MicroTime is version of Time with microsecond level precision.
type MicroTime struct {
	
}

func NewMicroTime() *MicroTime {
	return &MicroTime{}
}

func NewMicroTimeWithSpec(spec *MicroTime) *MicroTime {
	
	return spec
}

func RegisterMicroTime(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[MicroTime]()).JsNamespace("k8s.apimachinery.meta.v1").Fields(
		
	).Constructors(
		js.Constructor(reflect.ValueOf(NewMicroTime)),
		js.Constructor(reflect.ValueOf(NewMicroTimeWithSpec)),
	)
}