// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// Status is a return value for calls that don't return other objects.
type Status struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty" yaml:"apiVersion,omitempty"`

	// Suggested HTTP return code for this status, 0 if not set.
	Code *int `json:"code,omitempty" yaml:"code,omitempty"`

	// Extended data associated with the reason.  Each reason may define its own extended details. This field is optional and the data returned is not guaranteed to conform to any schema except that defined by the reason type.
	Details *StatusDetails `json:"details,omitempty" yaml:"details,omitempty"`

	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`

	// A human-readable description of the status of this operation.
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`

	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *ListMeta `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	// A machine-readable description of why this operation is in the "Failure" status. If this value is empty there is no information available. A Reason clarifies an HTTP status code but does not override it.
	Reason *string `json:"reason,omitempty" yaml:"reason,omitempty"`

	// Status of the operation. One of: "Success" or "Failure". More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
	Status *string `json:"status,omitempty" yaml:"status,omitempty"`
}

func NewStatus() *Status {
	return &Status{}
}

func NewStatusWithSpec(spec *Status) *Status {
	version := "v1"
	kind := "Status"
	
	spec.ApiVersion = &version
	spec.Kind = &kind
	return spec
}

func RegisterStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[Status]()).JsNamespace("k8s.apimachinery.meta.v1").Fields(
		js.Field("ApiVersion"),
		js.Field("Code"),
		js.Field("Details"),
		js.Field("Kind"),
		js.Field("Message"),
		js.Field("Metadata"),
		js.Field("Reason"),
		js.Field("Status"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewStatus)),
		js.Constructor(reflect.ValueOf(NewStatusWithSpec)),
	)
}