// Code generated by types_generator.go; DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewPodCertificateRequest(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "certificates.k8s.io/v1alpha1")
	document.Set("kind", "PodCertificateRequest")
	return document
}

func NewPodCertificateRequestWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "certificates.k8s.io/v1alpha1")
	document.Set("kind", "PodCertificateRequest")
	return document
}

func RegisterPodCertificateRequest(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewPodCertificateRequest)).JsModule("k8s/certificates/v1alpha1").JsName("PodCertificateRequest")
	jsRuntime.Constructor(reflect.ValueOf(NewPodCertificateRequestWithSpec)).JsModule("k8s/certificates/v1alpha1").JsName("PodCertificateRequest")
	
}