// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	corev1 "github.com/ohayocorp/anemos/pkg/k8s/core/v1"
)

// Endpoint represents a single logical "backend" implementing a service.
type Endpoint struct {
	// Addresses of this endpoint. For EndpointSlices of addressType "IPv4" or "IPv6", the values are IP addresses in canonical form. The syntax and semantics of other addressType values are not defined. This must contain at least one address but no more than 100. EndpointSlices generated by the EndpointSlice controller will always have exactly 1 address. No semantics are defined for additional addresses beyond the first, and kube-proxy does not look at them.
	Addresses []string `json:"addresses" yaml:"addresses"`

	// Conditions contains information about the current status of the endpoint.
	Conditions *EndpointConditions `json:"conditions,omitempty" yaml:"conditions,omitempty"`

	// DeprecatedTopology contains topology information part of the v1beta1 API. This field is deprecated, and will be removed when the v1beta1 API is removed (no sooner than kubernetes v1.24).  While this field can hold values, it is not writable through the v1 API, and any attempts to write to it will be silently ignored. Topology information can be found in the zone and nodeName fields instead.
	DeprecatedTopology map[string]string `json:"deprecatedTopology,omitempty" yaml:"deprecatedTopology,omitempty"`

	// Hints contains information associated with how an endpoint should be consumed.
	Hints *EndpointHints `json:"hints,omitempty" yaml:"hints,omitempty"`

	// Hostname of this endpoint. This field may be used by consumers of endpoints to distinguish endpoints from each other (e.g. in DNS names). Multiple endpoints which use the same hostname should be considered fungible (e.g. multiple A values in DNS). Must be lowercase and pass DNS Label (RFC 1123) validation.
	Hostname *string `json:"hostname,omitempty" yaml:"hostname,omitempty"`

	// NodeName represents the name of the Node hosting this endpoint. This can be used to determine endpoints local to a Node.
	NodeName *string `json:"nodeName,omitempty" yaml:"nodeName,omitempty"`

	// TargetRef is a reference to a Kubernetes object that represents this endpoint.
	TargetRef *corev1.ObjectReference `json:"targetRef,omitempty" yaml:"targetRef,omitempty"`

	// Zone is the name of the Zone this endpoint exists in.
	Zone *string `json:"zone,omitempty" yaml:"zone,omitempty"`
}

func NewEndpoint() *Endpoint {
	return &Endpoint{}
}

func NewEndpointWithSpec(spec *Endpoint) *Endpoint {
	
	return spec
}

func RegisterEndpoint(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[Endpoint]()).JsNamespace("k8s.discovery.v1").Fields(
		js.Field("Addresses"),
		js.Field("Conditions"),
		js.Field("DeprecatedTopology"),
		js.Field("Hints"),
		js.Field("Hostname"),
		js.Field("NodeName"),
		js.Field("TargetRef"),
		js.Field("Zone"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewEndpoint)),
		js.Constructor(reflect.ValueOf(NewEndpointWithSpec)),
	)
}