// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// EndpointConditions represents the current condition of an endpoint.
type EndpointConditions struct {
	// Ready indicates that this endpoint is ready to receive traffic, according to whatever system is managing the endpoint. A nil value should be interpreted as "true". In general, an endpoint should be marked ready if it is serving and not terminating, though this can be overridden in some cases, such as when the associated Service has set the publishNotReadyAddresses flag.
	Ready *bool `json:"ready,omitempty" yaml:"ready,omitempty"`

	// Serving indicates that this endpoint is able to receive traffic, according to whatever system is managing the endpoint. For endpoints backed by pods, the EndpointSlice controller will mark the endpoint as serving if the pod's Ready condition is True. A nil value should be interpreted as "true".
	Serving *bool `json:"serving,omitempty" yaml:"serving,omitempty"`

	// Terminating indicates that this endpoint is terminating. A nil value should be interpreted as "false".
	Terminating *bool `json:"terminating,omitempty" yaml:"terminating,omitempty"`
}

func NewEndpointConditions() *EndpointConditions {
	return &EndpointConditions{}
}

func NewEndpointConditionsWithSpec(spec *EndpointConditions) *EndpointConditions {
	
	return spec
}

func RegisterEndpointConditions(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[EndpointConditions]()).JsNamespace("k8s.discovery.v1").Fields(
		js.Field("Ready"),
		js.Field("Serving"),
		js.Field("Terminating"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewEndpointConditions)),
		js.Constructor(reflect.ValueOf(NewEndpointConditionsWithSpec)),
	)
}