// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewEndpointSlice(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "v1")
	document.Set("kind", "EndpointSlice")
	return document
}

func NewEndpointSliceWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "v1")
	document.Set("kind", "EndpointSlice")
	return document
}

func RegisterEndpointSlice(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewEndpointSlice)).JsNamespace("k8s.discovery.v1").JsName("EndpointSlice")
	jsRuntime.Constructor(reflect.ValueOf(NewEndpointSliceWithSpec)).JsNamespace("k8s.discovery.v1").JsName("EndpointSlice")
	
	jsRuntime.Constructor(reflect.ValueOf(NewEndpointSlice)).JsNamespace("k8s").JsName("EndpointSlice")
	jsRuntime.Constructor(reflect.ValueOf(NewEndpointSliceWithSpec)).JsNamespace("k8s").JsName("EndpointSlice")
	
}