// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// ForZone provides information about which zones should consume this endpoint.
type ForZone struct {
	// Name represents the name of the zone.
	Name string `json:"name" yaml:"name"`
}

func NewForZone() *ForZone {
	return &ForZone{}
}

func NewForZoneWithSpec(spec *ForZone) *ForZone {
	
	return spec
}

func RegisterForZone(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ForZone]()).JsNamespace("k8s.discovery.v1").Fields(
		js.Field("Name"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewForZone)),
		js.Constructor(reflect.ValueOf(NewForZoneWithSpec)),
	)
}