// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewPriorityLevelConfiguration(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "flowcontrol.apiserver.k8s.io/v1")
	document.Set("kind", "PriorityLevelConfiguration")
	return document
}

func NewPriorityLevelConfigurationWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "flowcontrol.apiserver.k8s.io/v1")
	document.Set("kind", "PriorityLevelConfiguration")
	return document
}

func RegisterPriorityLevelConfiguration(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewPriorityLevelConfiguration)).JsModule("k8s/flowcontrol/v1").JsName("PriorityLevelConfiguration")
	jsRuntime.Constructor(reflect.ValueOf(NewPriorityLevelConfigurationWithSpec)).JsModule("k8s/flowcontrol/v1").JsName("PriorityLevelConfiguration")
	
	jsRuntime.Constructor(reflect.ValueOf(NewPriorityLevelConfiguration)).JsModule("k8s").JsName("PriorityLevelConfiguration")
	jsRuntime.Constructor(reflect.ValueOf(NewPriorityLevelConfigurationWithSpec)).JsModule("k8s").JsName("PriorityLevelConfiguration")
	
}