// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// PriorityLevelConfigurationReference contains information that points to the "request-priority" being used.
type PriorityLevelConfigurationReference struct {
	// `name` is the name of the priority level configuration being referenced Required.
	Name string `json:"name" yaml:"name"`
}

func NewPriorityLevelConfigurationReference() *PriorityLevelConfigurationReference {
	return &PriorityLevelConfigurationReference{}
}

func NewPriorityLevelConfigurationReferenceWithSpec(spec *PriorityLevelConfigurationReference) *PriorityLevelConfigurationReference {
	
	return spec
}

func RegisterPriorityLevelConfigurationReference(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[PriorityLevelConfigurationReference]()).JsNamespace("k8s.flowcontrol.v1").Fields(
		js.Field("Name"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewPriorityLevelConfigurationReference)),
		js.Constructor(reflect.ValueOf(NewPriorityLevelConfigurationReferenceWithSpec)),
	)
}