// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// PriorityLevelConfigurationStatus represents the current state of a "request-priority".
type PriorityLevelConfigurationStatus struct {
	// `conditions` is the current state of "request-priority".
	Conditions []*PriorityLevelConfigurationCondition `json:"conditions,omitempty" yaml:"conditions,omitempty"`
}

func NewPriorityLevelConfigurationStatus() *PriorityLevelConfigurationStatus {
	return &PriorityLevelConfigurationStatus{}
}

func NewPriorityLevelConfigurationStatusWithSpec(spec *PriorityLevelConfigurationStatus) *PriorityLevelConfigurationStatus {
	
	return spec
}

func RegisterPriorityLevelConfigurationStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[PriorityLevelConfigurationStatus]()).JsNamespace("k8s.flowcontrol.v1").Fields(
		js.Field("Conditions"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewPriorityLevelConfigurationStatus)),
		js.Constructor(reflect.ValueOf(NewPriorityLevelConfigurationStatusWithSpec)),
	)
}