// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// ServiceAccountSubject holds detailed information for service-account-kind subject.
type ServiceAccountSubject struct {
	// `name` is the name of matching ServiceAccount objects, or "*" to match regardless of name. Required.
	Name string `json:"name" yaml:"name"`

	// `namespace` is the namespace of matching ServiceAccount objects. Required.
	Namespace string `json:"namespace" yaml:"namespace"`
}

func NewServiceAccountSubject() *ServiceAccountSubject {
	return &ServiceAccountSubject{}
}

func NewServiceAccountSubjectWithSpec(spec *ServiceAccountSubject) *ServiceAccountSubject {
	
	return spec
}

func RegisterServiceAccountSubject(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ServiceAccountSubject]()).JsNamespace("k8s.flowcontrol.v1").Fields(
		js.Field("Name"),
		js.Field("Namespace"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewServiceAccountSubject)),
		js.Constructor(reflect.ValueOf(NewServiceAccountSubjectWithSpec)),
	)
}