// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// UserSubject holds detailed information for user-kind subject.
type UserSubject struct {
	// `name` is the username that matches, or "*" to match all usernames. Required.
	Name string `json:"name" yaml:"name"`
}

func NewUserSubject() *UserSubject {
	return &UserSubject{}
}

func NewUserSubjectWithSpec(spec *UserSubject) *UserSubject {
	
	return spec
}

func RegisterUserSubject(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[UserSubject]()).JsNamespace("k8s.flowcontrol.v1").Fields(
		js.Field("Name"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewUserSubject)),
		js.Constructor(reflect.ValueOf(NewUserSubjectWithSpec)),
	)
}