// Code generated by types_generator.go; DO NOT EDIT.

package v1beta1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
)

// ServiceCIDRStatus describes the current state of the ServiceCIDR.
type ServiceCIDRStatus struct {
	// Conditions holds an array of metav1.Condition that describe the state of the ServiceCIDR. Current service state
	Conditions []*apimachinerymetav1.Condition `json:"conditions,omitempty" yaml:"conditions,omitempty"`
}

func NewServiceCIDRStatus() *ServiceCIDRStatus {
	return &ServiceCIDRStatus{}
}

func NewServiceCIDRStatusWithSpec(spec *ServiceCIDRStatus) *ServiceCIDRStatus {
	
	return spec
}

func RegisterServiceCIDRStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ServiceCIDRStatus]()).JsNamespace("k8s.networking.v1beta1").Fields(
		js.Field("Conditions"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewServiceCIDRStatus)),
		js.Constructor(reflect.ValueOf(NewServiceCIDRStatusWithSpec)),
	)
}