// Code generated by types_generator.go; DO NOT EDIT.

package v1alpha2

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// LeaseCandidateSpec is a specification of a Lease.
type LeaseCandidateSpec struct {
	// BinaryVersion is the binary version. It must be in a semver format without leading `v`. This field is required.
	BinaryVersion string `json:"binaryVersion" yaml:"binaryVersion"`

	// EmulationVersion is the emulation version. It must be in a semver format without leading `v`. EmulationVersion must be less than or equal to BinaryVersion. This field is required when strategy is "OldestEmulationVersion"
	EmulationVersion *string `json:"emulationVersion,omitempty" yaml:"emulationVersion,omitempty"`

	// LeaseName is the name of the lease for which this candidate is contending. This field is immutable.
	LeaseName string `json:"leaseName" yaml:"leaseName"`

	// PingTime is the last time that the server has requested the LeaseCandidate to renew. It is only done during leader election to check if any LeaseCandidates have become ineligible. When PingTime is updated, the LeaseCandidate will respond by updating RenewTime.
	PingTime *string `json:"pingTime,omitempty" yaml:"pingTime,omitempty"`

	// RenewTime is the time that the LeaseCandidate was last updated. Any time a Lease needs to do leader election, the PingTime field is updated to signal to the LeaseCandidate that they should update the RenewTime. Old LeaseCandidate objects are also garbage collected if it has been hours since the last renew. The PingTime field is updated regularly to prevent garbage collection for still active LeaseCandidates.
	RenewTime *string `json:"renewTime,omitempty" yaml:"renewTime,omitempty"`

	// Strategy is the strategy that coordinated leader election will use for picking the leader. If multiple candidates for the same Lease return different strategies, the strategy provided by the candidate with the latest BinaryVersion will be used. If there is still conflict, this is a user error and coordinated leader election will not operate the Lease until resolved.
	Strategy string `json:"strategy" yaml:"strategy"`
}

func NewLeaseCandidateSpec() *LeaseCandidateSpec {
	return &LeaseCandidateSpec{}
}

func NewLeaseCandidateSpecWithSpec(spec *LeaseCandidateSpec) *LeaseCandidateSpec {
	
	return spec
}

func RegisterLeaseCandidateSpec(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[LeaseCandidateSpec]()).JsNamespace("k8s.coordination.v1alpha2").Fields(
		js.Field("BinaryVersion"),
		js.Field("EmulationVersion"),
		js.Field("LeaseName"),
		js.Field("PingTime"),
		js.Field("RenewTime"),
		js.Field("Strategy"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewLeaseCandidateSpec)),
		js.Constructor(reflect.ValueOf(NewLeaseCandidateSpecWithSpec)),
	)
}