// Code generated by types_generator.go; DO NOT EDIT.

package v1alpha2

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
)

// LeaseCandidate defines a candidate for a Lease object. Candidates are created such that coordinated leader election will pick the best leader from the list of candidates.
type LeaseCandidate struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty" yaml:"apiVersion,omitempty"`

	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`

	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *apimachinerymetav1.ObjectMeta `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	// Spec contains the specification of the Lease. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
	Spec *LeaseCandidateSpec `json:"spec,omitempty" yaml:"spec,omitempty"`
}

func NewLeaseCandidate() *LeaseCandidate {
	return &LeaseCandidate{}
}

func NewLeaseCandidateWithSpec(spec *LeaseCandidate) *LeaseCandidate {
	version := "v1alpha2"
	kind := "LeaseCandidate"
	
	spec.ApiVersion = &version
	spec.Kind = &kind
	return spec
}

func RegisterLeaseCandidate(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[LeaseCandidate]()).JsNamespace("k8s.coordination.v1alpha2").Fields(
		js.Field("ApiVersion"),
		js.Field("Kind"),
		js.Field("Metadata"),
		js.Field("Spec"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewLeaseCandidate)),
		js.Constructor(reflect.ValueOf(NewLeaseCandidateWithSpec)),
	)
}