// Code generated by types_generator.go; DO NOT EDIT.

package v1beta2

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// The device this taint is attached to has the "effect" on any claim which does not tolerate the taint and, through the claim, to pods using the claim.
type DeviceTaint struct {
	// The effect of the taint on claims that do not tolerate the taint and through such claims on the pods using them. Valid effects are NoSchedule and NoExecute. PreferNoSchedule as used for nodes is not valid here.
	Effect string `json:"effect" yaml:"effect"`

	// The taint key to be applied to a device. Must be a label name.
	Key string `json:"key" yaml:"key"`

	// TimeAdded represents the time at which the taint was added. Added automatically during create or update if not set.
	TimeAdded *string `json:"timeAdded,omitempty" yaml:"timeAdded,omitempty"`

	// The taint value corresponding to the taint key. Must be a label value.
	Value *string `json:"value,omitempty" yaml:"value,omitempty"`
}

func NewDeviceTaint() *DeviceTaint {
	return &DeviceTaint{}
}

func NewDeviceTaintWithSpec(spec *DeviceTaint) *DeviceTaint {
	
	return spec
}

func RegisterDeviceTaint(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[DeviceTaint]()).JsNamespace("k8s.resource.v1beta2").Fields(
		js.Field("Effect"),
		js.Field("Key"),
		js.Field("TimeAdded"),
		js.Field("Value"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewDeviceTaint)),
		js.Constructor(reflect.ValueOf(NewDeviceTaintWithSpec)),
	)
}