// Code generated by types_generator.go; DO NOT EDIT.

package v1beta2

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// The ResourceClaim this DeviceToleration is attached to tolerates any taint that matches the triple <key,value,effect> using the matching operator <operator>.
type DeviceToleration struct {
	// Effect indicates the taint effect to match. Empty means match all taint effects. When specified, allowed values are NoSchedule and NoExecute.
	Effect *string `json:"effect,omitempty" yaml:"effect,omitempty"`

	// Key is the taint key that the toleration applies to. Empty means match all taint keys. If the key is empty, operator must be Exists; this combination means to match all values and all keys. Must be a label name.
	Key *string `json:"key,omitempty" yaml:"key,omitempty"`

	// Operator represents a key's relationship to the value. Valid operators are Exists and Equal. Defaults to Equal. Exists is equivalent to wildcard for value, so that a ResourceClaim can tolerate all taints of a particular category.
	Operator *string `json:"operator,omitempty" yaml:"operator,omitempty"`

	// TolerationSeconds represents the period of time the toleration (which must be of effect NoExecute, otherwise this field is ignored) tolerates the taint. By default, it is not set, which means tolerate the taint forever (do not evict). Zero and negative values will be treated as 0 (evict immediately) by the system. If larger than zero, the time when the pod needs to be evicted is calculated as <time when taint was adedd> + <toleration seconds>.
	TolerationSeconds *int `json:"tolerationSeconds,omitempty" yaml:"tolerationSeconds,omitempty"`

	// Value is the taint value the toleration matches to. If the operator is Exists, the value must be empty, otherwise just a regular string. Must be a label value.
	Value *string `json:"value,omitempty" yaml:"value,omitempty"`
}

func NewDeviceToleration() *DeviceToleration {
	return &DeviceToleration{}
}

func NewDeviceTolerationWithSpec(spec *DeviceToleration) *DeviceToleration {
	
	return spec
}

func RegisterDeviceToleration(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[DeviceToleration]()).JsNamespace("k8s.resource.v1beta2").Fields(
		js.Field("Effect"),
		js.Field("Key"),
		js.Field("Operator"),
		js.Field("TolerationSeconds"),
		js.Field("Value"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewDeviceToleration)),
		js.Constructor(reflect.ValueOf(NewDeviceTolerationWithSpec)),
	)
}