// Code generated by types_generator.go; DO NOT EDIT.

package v1beta2

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	corev1 "github.com/ohayocorp/anemos/pkg/k8s/core/v1"
)

// Device represents one individual hardware instance that can be selected based on its attributes. Besides the name, exactly one field must be set.
type Device struct {
	// AllNodes indicates that all nodes have access to the device.
	// Must only be set if Spec.PerDeviceNodeSelection is set to true. At most one of NodeName, NodeSelector and AllNodes can be set.
	AllNodes *bool `json:"allNodes,omitempty" yaml:"allNodes,omitempty"`

	// AllowMultipleAllocations marks whether the device is allowed to be allocated to multiple DeviceRequests.
	// If AllowMultipleAllocations is set to true, the device can be allocated more than once, and all of its capacity is consumable, regardless of whether the requestPolicy is defined or not.
	AllowMultipleAllocations *bool `json:"allowMultipleAllocations,omitempty" yaml:"allowMultipleAllocations,omitempty"`

	// Attributes defines the set of attributes for this device. The name of each attribute must be unique in that set.
	// The maximum number of attributes and capacities combined is 32.
	Attributes *any `json:"attributes,omitempty" yaml:"attributes,omitempty"`

	// BindingConditions defines the conditions for proceeding with binding. All of these conditions must be set in the per-device status conditions with a value of True to proceed with binding the pod to the node while scheduling the pod.
	// The maximum number of binding conditions is 4.
	// The conditions must be a valid condition type string.
	// This is an alpha field and requires enabling the DRADeviceBindingConditions and DRAResourceClaimDeviceStatus feature gates.
	BindingConditions *[]string `json:"bindingConditions,omitempty" yaml:"bindingConditions,omitempty"`

	// BindingFailureConditions defines the conditions for binding failure. They may be set in the per-device status conditions. If any is set to "True", a binding failure occurred.
	// The maximum number of binding failure conditions is 4.
	// The conditions must be a valid condition type string.
	// This is an alpha field and requires enabling the DRADeviceBindingConditions and DRAResourceClaimDeviceStatus feature gates.
	BindingFailureConditions *[]string `json:"bindingFailureConditions,omitempty" yaml:"bindingFailureConditions,omitempty"`

	// BindsToNode indicates if the usage of an allocation involving this device has to be limited to exactly the node that was chosen when allocating the claim. If set to true, the scheduler will set the ResourceClaim.Status.Allocation.NodeSelector to match the node where the allocation was made.
	// This is an alpha field and requires enabling the DRADeviceBindingConditions and DRAResourceClaimDeviceStatus feature gates.
	BindsToNode *bool `json:"bindsToNode,omitempty" yaml:"bindsToNode,omitempty"`

	// Capacity defines the set of capacities for this device. The name of each capacity must be unique in that set.
	// The maximum number of attributes and capacities combined is 32.
	Capacity *any `json:"capacity,omitempty" yaml:"capacity,omitempty"`

	// ConsumesCounters defines a list of references to sharedCounters and the set of counters that the device will consume from those counter sets.
	// There can only be a single entry per counterSet.
	// The total number of device counter consumption entries must be <= 32. In addition, the total number in the entire ResourceSlice must be <= 1024 (for example, 64 devices with 16 counters each).
	ConsumesCounters []*DeviceCounterConsumption `json:"consumesCounters,omitempty" yaml:"consumesCounters,omitempty"`

	// Name is unique identifier among all devices managed by the driver in the pool. It must be a DNS label.
	Name string `json:"name" yaml:"name"`

	// NodeName identifies the node where the device is available.
	// Must only be set if Spec.PerDeviceNodeSelection is set to true. At most one of NodeName, NodeSelector and AllNodes can be set.
	NodeName *string `json:"nodeName,omitempty" yaml:"nodeName,omitempty"`

	// NodeSelector defines the nodes where the device is available.
	// Must use exactly one term.
	// Must only be set if Spec.PerDeviceNodeSelection is set to true. At most one of NodeName, NodeSelector and AllNodes can be set.
	NodeSelector *corev1.NodeSelector `json:"nodeSelector,omitempty" yaml:"nodeSelector,omitempty"`

	// If specified, these are the driver-defined taints.
	// The maximum number of taints is 4.
	// This is an alpha field and requires enabling the DRADeviceTaints feature gate.
	Taints []*DeviceTaint `json:"taints,omitempty" yaml:"taints,omitempty"`
}

func NewDevice() *Device {
	return &Device{}
}

func NewDeviceWithSpec(spec *Device) *Device {
	
	return spec
}

func RegisterDevice(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[Device]()).JsNamespace("k8s.resource.v1beta2").Fields(
		js.Field("AllNodes"),
		js.Field("AllowMultipleAllocations"),
		js.Field("Attributes"),
		js.Field("BindingConditions"),
		js.Field("BindingFailureConditions"),
		js.Field("BindsToNode"),
		js.Field("Capacity"),
		js.Field("ConsumesCounters"),
		js.Field("Name"),
		js.Field("NodeName"),
		js.Field("NodeSelector"),
		js.Field("Taints"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewDevice)),
		js.Constructor(reflect.ValueOf(NewDeviceWithSpec)),
	)
}