// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// CertificateSigningRequestStatus contains conditions used to indicate approved/denied/failed status of the request, and the issued certificate.
type CertificateSigningRequestStatus struct {
	// Certificate is populated with an issued certificate by the signer after an Approved condition is present. This field is set via the /status subresource. Once populated, this field is immutable.
	// If the certificate signing request is denied, a condition of type "Denied" is added and this field remains empty. If the signer cannot issue the certificate, a condition of type "Failed" is added and this field remains empty.
	// Validation requirements:
	//  1. certificate must contain one or more PEM blocks.
	//  2. All PEM blocks must have the "CERTIFICATE" label, contain no headers, and the encoded data
	//   must be a BER-encoded ASN.1 Certificate structure as described in section 4 of RFC5280.
	//  3. Non-PEM content may appear before or after the "CERTIFICATE" PEM blocks and is unvalidated,
	//   to allow for explanatory text as described in section 5.2 of RFC7468.
	// If more than one PEM block is present, and the definition of the requested spec.signerName does not indicate otherwise, the first block is the issued certificate, and subsequent blocks should be treated as intermediate certificates and presented in TLS handshakes.
	// The certificate is encoded in PEM format.
	// When serialized as JSON or YAML, the data is additionally base64-encoded, so it consists of:
	//     base64(
	//     -----BEGIN CERTIFICATE-----
	//     ...
	//     -----END CERTIFICATE-----
	//     )
	Certificate *string `json:"certificate,omitempty" yaml:"certificate,omitempty"`

	// Conditions applied to the request. Known conditions are "Approved", "Denied", and "Failed".
	Conditions []*CertificateSigningRequestCondition `json:"conditions,omitempty" yaml:"conditions,omitempty"`
}

func NewCertificateSigningRequestStatus() *CertificateSigningRequestStatus {
	return &CertificateSigningRequestStatus{}
}

func NewCertificateSigningRequestStatusWithSpec(spec *CertificateSigningRequestStatus) *CertificateSigningRequestStatus {
	
	return spec
}

func RegisterCertificateSigningRequestStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[CertificateSigningRequestStatus]()).JsNamespace("k8s.certificates.v1").Fields(
		js.Field("Certificate"),
		js.Field("Conditions"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewCertificateSigningRequestStatus)),
		js.Constructor(reflect.ValueOf(NewCertificateSigningRequestStatusWithSpec)),
	)
}