// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewRoleBinding(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "rbac.authorization.k8s.io/v1")
	document.Set("kind", "RoleBinding")
	return document
}

func NewRoleBindingWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "rbac.authorization.k8s.io/v1")
	document.Set("kind", "RoleBinding")
	return document
}

func RegisterRoleBinding(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewRoleBinding)).JsModule("k8s/rbac/v1").JsName("RoleBinding")
	jsRuntime.Constructor(reflect.ValueOf(NewRoleBindingWithSpec)).JsModule("k8s/rbac/v1").JsName("RoleBinding")
	
	jsRuntime.Constructor(reflect.ValueOf(NewRoleBinding)).JsModule("k8s").JsName("RoleBinding")
	jsRuntime.Constructor(reflect.ValueOf(NewRoleBindingWithSpec)).JsModule("k8s").JsName("RoleBinding")
	
}