// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// Subject contains a reference to the object or user identities a role binding applies to.  This can either hold a direct API object reference, or a value for non-objects such as user and group names.
type Subject struct {
	// APIGroup holds the API group of the referenced subject. Defaults to "" for ServiceAccount subjects. Defaults to "rbac.authorization.k8s.io" for User and Group subjects.
	ApiGroup *string `json:"apiGroup,omitempty" yaml:"apiGroup,omitempty"`

	// Kind of object being referenced. Values defined by this API group are "User", "Group", and "ServiceAccount". If the Authorizer does not recognized the kind value, the Authorizer should report an error.
	Kind string `json:"kind" yaml:"kind"`

	// Name of the object being referenced.
	Name string `json:"name" yaml:"name"`

	// Namespace of the referenced object.  If the object kind is non-namespace, such as "User" or "Group", and this value is not empty the Authorizer should report an error.
	Namespace *string `json:"namespace,omitempty" yaml:"namespace,omitempty"`
}

func NewSubject() *Subject {
	return &Subject{}
}

func NewSubjectWithSpec(spec *Subject) *Subject {
	
	return spec
}

func RegisterSubject(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[Subject]()).JsNamespace("k8s.rbac.v1").Fields(
		js.Field("ApiGroup"),
		js.Field("Kind"),
		js.Field("Name"),
		js.Field("Namespace"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewSubject)),
		js.Constructor(reflect.ValueOf(NewSubjectWithSpec)),
	)
}