// Code generated by types_generator.go; DO NOT EDIT.

package v1alpha3

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// DeviceTaintSelector defines which device(s) a DeviceTaintRule applies to. The empty selector matches all devices. Without a selector, no devices are matched.
type DeviceTaintSelector struct {
	// If device is set, only devices with that name are selected. This field corresponds to slice.spec.devices[].name.
	// Setting also driver and pool may be required to avoid ambiguity, but is not required.
	Device *string `json:"device,omitempty" yaml:"device,omitempty"`

	// If DeviceClassName is set, the selectors defined there must be satisfied by a device to be selected. This field corresponds to class.metadata.name.
	DeviceClassName *string `json:"deviceClassName,omitempty" yaml:"deviceClassName,omitempty"`

	// If driver is set, only devices from that driver are selected. This fields corresponds to slice.spec.driver.
	Driver *string `json:"driver,omitempty" yaml:"driver,omitempty"`

	// If pool is set, only devices in that pool are selected.
	// Also setting the driver name may be useful to avoid ambiguity when different drivers use the same pool name, but this is not required because selecting pools from different drivers may also be useful, for example when drivers with node-local devices use the node name as their pool name.
	Pool *string `json:"pool,omitempty" yaml:"pool,omitempty"`

	// Selectors contains the same selection criteria as a ResourceClaim. Currently, CEL expressions are supported. All of these selectors must be satisfied.
	Selectors []*DeviceSelector `json:"selectors,omitempty" yaml:"selectors,omitempty"`
}

func NewDeviceTaintSelector() *DeviceTaintSelector {
	return &DeviceTaintSelector{}
}

func NewDeviceTaintSelectorWithSpec(spec *DeviceTaintSelector) *DeviceTaintSelector {
	
	return spec
}

func RegisterDeviceTaintSelector(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[DeviceTaintSelector]()).JsNamespace("k8s.resource.v1alpha3").Fields(
		js.Field("Device"),
		js.Field("DeviceClassName"),
		js.Field("Driver"),
		js.Field("Pool"),
		js.Field("Selectors"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewDeviceTaintSelector)),
		js.Constructor(reflect.ValueOf(NewDeviceTaintSelectorWithSpec)),
	)
}