// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewMutatingWebhookConfiguration(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "v1")
	document.Set("kind", "MutatingWebhookConfiguration")
	return document
}

func NewMutatingWebhookConfigurationWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "v1")
	document.Set("kind", "MutatingWebhookConfiguration")
	return document
}

func RegisterMutatingWebhookConfiguration(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewMutatingWebhookConfiguration)).JsNamespace("k8s.admissionregistration.v1").JsName("MutatingWebhookConfiguration")
	jsRuntime.Constructor(reflect.ValueOf(NewMutatingWebhookConfigurationWithSpec)).JsNamespace("k8s.admissionregistration.v1").JsName("MutatingWebhookConfiguration")
	
	jsRuntime.Constructor(reflect.ValueOf(NewMutatingWebhookConfiguration)).JsNamespace("k8s").JsName("MutatingWebhookConfiguration")
	jsRuntime.Constructor(reflect.ValueOf(NewMutatingWebhookConfigurationWithSpec)).JsNamespace("k8s").JsName("MutatingWebhookConfiguration")
	
}