// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
)

// ParamRef describes how to locate the params to be used as input to expressions of rules applied by a policy binding.
type ParamRef struct {
	// Name is the name of the resource being referenced.
	// One of `name` or `selector` must be set, but `name` and `selector` are mutually exclusive properties. If one is set, the other must be unset.
	// A single parameter used for all admission requests can be configured by setting the `name` field, leaving `selector` blank, and setting namespace if `paramKind` is namespace-scoped.
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`

	// Namespace is the namespace of the referenced resource. Allows limiting the search for params to a specific namespace. Applies to both `name` and `selector` fields.
	// A per-namespace parameter may be used by specifying a namespace-scoped `paramKind` in the policy and leaving this field empty.
	// - If `paramKind` is cluster-scoped, this field MUST be unset. Setting this field results in a configuration error.
	// - If `paramKind` is namespace-scoped, the namespace of the object being evaluated for admission will be used when this field is left unset. Take care that if this is left empty the binding must not match any cluster-scoped resources, which will result in an error.
	Namespace *string `json:"namespace,omitempty" yaml:"namespace,omitempty"`

	// `parameterNotFoundAction` controls the behavior of the binding when the resource exists, and name or selector is valid, but there are no parameters matched by the binding. If the value is set to `Allow`, then no matched parameters will be treated as successful validation by the binding. If set to `Deny`, then no matched parameters will be subject to the `failurePolicy` of the policy.
	// Allowed values are `Allow` or `Deny`
	// Required
	ParameterNotFoundAction *string `json:"parameterNotFoundAction,omitempty" yaml:"parameterNotFoundAction,omitempty"`

	// Selector can be used to match multiple param objects based on their labels. Supply selector: {} to match all resources of the ParamKind.
	// If multiple params are found, they are all evaluated with the policy expressions and the results are ANDed together.
	// One of `name` or `selector` must be set, but `name` and `selector` are mutually exclusive properties. If one is set, the other must be unset.
	Selector *apimachinerymetav1.LabelSelector `json:"selector,omitempty" yaml:"selector,omitempty"`
}

func NewParamRef() *ParamRef {
	return &ParamRef{}
}

func NewParamRefWithSpec(spec *ParamRef) *ParamRef {
	
	return spec
}

func RegisterParamRef(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ParamRef]()).JsNamespace("k8s.admissionregistration.v1").Fields(
		js.Field("Name"),
		js.Field("Namespace"),
		js.Field("ParameterNotFoundAction"),
		js.Field("Selector"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewParamRef)),
		js.Constructor(reflect.ValueOf(NewParamRefWithSpec)),
	)
}