// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// TypeChecking contains results of type checking the expressions in the ValidatingAdmissionPolicy
type TypeChecking struct {
	// The type checking warnings for each expression.
	ExpressionWarnings []*ExpressionWarning `json:"expressionWarnings,omitempty" yaml:"expressionWarnings,omitempty"`
}

func NewTypeChecking() *TypeChecking {
	return &TypeChecking{}
}

func NewTypeCheckingWithSpec(spec *TypeChecking) *TypeChecking {
	
	return spec
}

func RegisterTypeChecking(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[TypeChecking]()).JsNamespace("k8s.admissionregistration.v1").Fields(
		js.Field("ExpressionWarnings"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewTypeChecking)),
		js.Constructor(reflect.ValueOf(NewTypeCheckingWithSpec)),
	)
}