// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewValidatingAdmissionPolicy(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "v1")
	document.Set("kind", "ValidatingAdmissionPolicy")
	return document
}

func NewValidatingAdmissionPolicyWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "v1")
	document.Set("kind", "ValidatingAdmissionPolicy")
	return document
}

func RegisterValidatingAdmissionPolicy(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewValidatingAdmissionPolicy)).JsNamespace("k8s.admissionregistration.v1").JsName("ValidatingAdmissionPolicy")
	jsRuntime.Constructor(reflect.ValueOf(NewValidatingAdmissionPolicyWithSpec)).JsNamespace("k8s.admissionregistration.v1").JsName("ValidatingAdmissionPolicy")
	
	jsRuntime.Constructor(reflect.ValueOf(NewValidatingAdmissionPolicy)).JsNamespace("k8s").JsName("ValidatingAdmissionPolicy")
	jsRuntime.Constructor(reflect.ValueOf(NewValidatingAdmissionPolicyWithSpec)).JsNamespace("k8s").JsName("ValidatingAdmissionPolicy")
	
}