// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewValidatingAdmissionPolicyBinding(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "admissionregistration.k8s.io/v1")
	document.Set("kind", "ValidatingAdmissionPolicyBinding")
	return document
}

func NewValidatingAdmissionPolicyBindingWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "admissionregistration.k8s.io/v1")
	document.Set("kind", "ValidatingAdmissionPolicyBinding")
	return document
}

func RegisterValidatingAdmissionPolicyBinding(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewValidatingAdmissionPolicyBinding)).JsModule("k8s/admissionregistration/v1").JsName("ValidatingAdmissionPolicyBinding")
	jsRuntime.Constructor(reflect.ValueOf(NewValidatingAdmissionPolicyBindingWithSpec)).JsModule("k8s/admissionregistration/v1").JsName("ValidatingAdmissionPolicyBinding")
	
	jsRuntime.Constructor(reflect.ValueOf(NewValidatingAdmissionPolicyBinding)).JsModule("k8s").JsName("ValidatingAdmissionPolicyBinding")
	jsRuntime.Constructor(reflect.ValueOf(NewValidatingAdmissionPolicyBindingWithSpec)).JsModule("k8s").JsName("ValidatingAdmissionPolicyBinding")
	
}