// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// ResourceAttributes includes the authorization attributes available for resource requests to the Authorizer interface
type ResourceAttributes struct {
	// FieldSelector describes the limitation on access based on field.  It can only limit access, not broaden it.
	FieldSelector *FieldSelectorAttributes `json:"fieldSelector,omitempty" yaml:"fieldSelector,omitempty"`

	// Group is the API Group of the Resource.  "*" means all.
	Group *string `json:"group,omitempty" yaml:"group,omitempty"`

	// LabelSelector describes the limitation on access based on labels.  It can only limit access, not broaden it.
	LabelSelector *LabelSelectorAttributes `json:"labelSelector,omitempty" yaml:"labelSelector,omitempty"`

	// Name is the name of the resource being requested for a "get" or deleted for a "delete". "" (empty) means all.
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`

	// Namespace is the namespace of the action being requested.  Currently, there is no distinction between no namespace and all namespaces "" (empty) is defaulted for LocalSubjectAccessReviews "" (empty) is empty for cluster-scoped resources "" (empty) means "all" for namespace scoped resources from a SubjectAccessReview or SelfSubjectAccessReview
	Namespace *string `json:"namespace,omitempty" yaml:"namespace,omitempty"`

	// Resource is one of the existing resource types.  "*" means all.
	Resource *string `json:"resource,omitempty" yaml:"resource,omitempty"`

	// Subresource is one of the existing resource types.  "" means none.
	Subresource *string `json:"subresource,omitempty" yaml:"subresource,omitempty"`

	// Verb is a kubernetes resource API verb, like: get, list, watch, create, update, delete, proxy.  "*" means all.
	Verb *string `json:"verb,omitempty" yaml:"verb,omitempty"`

	// Version is the API Version of the Resource.  "*" means all.
	Version *string `json:"version,omitempty" yaml:"version,omitempty"`
}

func NewResourceAttributes() *ResourceAttributes {
	return &ResourceAttributes{}
}

func NewResourceAttributesWithSpec(spec *ResourceAttributes) *ResourceAttributes {
	
	return spec
}

func RegisterResourceAttributes(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ResourceAttributes]()).JsNamespace("k8s.authorization.v1").Fields(
		js.Field("FieldSelector"),
		js.Field("Group"),
		js.Field("LabelSelector"),
		js.Field("Name"),
		js.Field("Namespace"),
		js.Field("Resource"),
		js.Field("Subresource"),
		js.Field("Verb"),
		js.Field("Version"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewResourceAttributes)),
		js.Constructor(reflect.ValueOf(NewResourceAttributesWithSpec)),
	)
}