// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// SelfSubjectAccessReviewSpec is a description of the access request.  Exactly one of ResourceAuthorizationAttributes and NonResourceAuthorizationAttributes must be set
type SelfSubjectAccessReviewSpec struct {
	// NonResourceAttributes describes information for a non-resource access request
	NonResourceAttributes *NonResourceAttributes `json:"nonResourceAttributes,omitempty" yaml:"nonResourceAttributes,omitempty"`

	// ResourceAuthorizationAttributes describes information for a resource access request
	ResourceAttributes *ResourceAttributes `json:"resourceAttributes,omitempty" yaml:"resourceAttributes,omitempty"`
}

func NewSelfSubjectAccessReviewSpec() *SelfSubjectAccessReviewSpec {
	return &SelfSubjectAccessReviewSpec{}
}

func NewSelfSubjectAccessReviewSpecWithSpec(spec *SelfSubjectAccessReviewSpec) *SelfSubjectAccessReviewSpec {
	
	return spec
}

func RegisterSelfSubjectAccessReviewSpec(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[SelfSubjectAccessReviewSpec]()).JsNamespace("k8s.authorization.v1").Fields(
		js.Field("NonResourceAttributes"),
		js.Field("ResourceAttributes"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewSelfSubjectAccessReviewSpec)),
		js.Constructor(reflect.ValueOf(NewSelfSubjectAccessReviewSpecWithSpec)),
	)
}