// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
)

// SubjectAccessReview checks whether or not a user or group can perform an action.
type SubjectAccessReview struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty" yaml:"apiVersion,omitempty"`

	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`

	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *apimachinerymetav1.ObjectMeta `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	// Spec holds information about the request being evaluated
	Spec *SubjectAccessReviewSpec `json:"spec" yaml:"spec"`

	// Status is filled in by the server and indicates whether the request is allowed or not
	Status *SubjectAccessReviewStatus `json:"status,omitempty" yaml:"status,omitempty"`
}

func NewSubjectAccessReview() *SubjectAccessReview {
	return &SubjectAccessReview{}
}

func NewSubjectAccessReviewWithSpec(spec *SubjectAccessReview) *SubjectAccessReview {
	version := "v1"
	kind := "SubjectAccessReview"
	
	spec.ApiVersion = &version
	spec.Kind = &kind
	return spec
}

func RegisterSubjectAccessReview(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[SubjectAccessReview]()).JsNamespace("k8s.authorization.v1").Fields(
		js.Field("ApiVersion"),
		js.Field("Kind"),
		js.Field("Metadata"),
		js.Field("Spec"),
		js.Field("Status"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewSubjectAccessReview)),
		js.Constructor(reflect.ValueOf(NewSubjectAccessReviewWithSpec)),
	)
}