// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// IngressClassSpec provides information about the class of an Ingress.
type IngressClassSpec struct {
	// Controller refers to the name of the controller that should handle this class. This allows for different "flavors" that are controlled by the same controller. For example, you may have different parameters for the same implementing controller. This should be specified as a domain-prefixed path no more than 250 characters in length, e.g. "acme.io/ingress-controller". This field is immutable.
	Controller *string `json:"controller,omitempty" yaml:"controller,omitempty"`

	// Parameters is a link to a custom resource containing additional configuration for the controller. This is optional if the controller does not require extra parameters.
	Parameters *IngressClassParametersReference `json:"parameters,omitempty" yaml:"parameters,omitempty"`
}

func NewIngressClassSpec() *IngressClassSpec {
	return &IngressClassSpec{}
}

func NewIngressClassSpecWithSpec(spec *IngressClassSpec) *IngressClassSpec {
	
	return spec
}

func RegisterIngressClassSpec(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[IngressClassSpec]()).JsNamespace("k8s.networking.v1").Fields(
		js.Field("Controller"),
		js.Field("Parameters"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewIngressClassSpec)),
		js.Constructor(reflect.ValueOf(NewIngressClassSpecWithSpec)),
	)
}