// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewIngressClass(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "v1")
	document.Set("kind", "IngressClass")
	return document
}

func NewIngressClassWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "v1")
	document.Set("kind", "IngressClass")
	return document
}

func RegisterIngressClass(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewIngressClass)).JsModule("k8s/networking/v1").JsName("IngressClass")
	jsRuntime.Constructor(reflect.ValueOf(NewIngressClassWithSpec)).JsModule("k8s/networking/v1").JsName("IngressClass")
	
	jsRuntime.Constructor(reflect.ValueOf(NewIngressClass)).JsModule("k8s").JsName("IngressClass")
	jsRuntime.Constructor(reflect.ValueOf(NewIngressClassWithSpec)).JsModule("k8s").JsName("IngressClass")
	
}