// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// IngressServiceBackend references a Kubernetes Service as a Backend.
type IngressServiceBackend struct {
	// Name is the referenced service. The service must exist in the same namespace as the Ingress object.
	Name string `json:"name" yaml:"name"`

	// Port of the referenced service. A port name or port number is required for a IngressServiceBackend.
	Port *ServiceBackendPort `json:"port,omitempty" yaml:"port,omitempty"`
}

func NewIngressServiceBackend() *IngressServiceBackend {
	return &IngressServiceBackend{}
}

func NewIngressServiceBackendWithSpec(spec *IngressServiceBackend) *IngressServiceBackend {
	
	return spec
}

func RegisterIngressServiceBackend(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[IngressServiceBackend]()).JsNamespace("k8s.networking.v1").Fields(
		js.Field("Name"),
		js.Field("Port"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewIngressServiceBackend)),
		js.Constructor(reflect.ValueOf(NewIngressServiceBackendWithSpec)),
	)
}