// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// IngressStatus describe the current state of the Ingress.
type IngressStatus struct {
	// LoadBalancer contains the current status of the load-balancer.
	LoadBalancer *IngressLoadBalancerStatus `json:"loadBalancer,omitempty" yaml:"loadBalancer,omitempty"`
}

func NewIngressStatus() *IngressStatus {
	return &IngressStatus{}
}

func NewIngressStatusWithSpec(spec *IngressStatus) *IngressStatus {
	
	return spec
}

func RegisterIngressStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[IngressStatus]()).JsNamespace("k8s.networking.v1").Fields(
		js.Field("LoadBalancer"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewIngressStatus)),
		js.Constructor(reflect.ValueOf(NewIngressStatusWithSpec)),
	)
}