// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// NetworkPolicyPort describes a port to allow traffic on
type NetworkPolicyPort struct {
	// EndPort indicates that the range of ports from port to endPort if set, inclusive, should be allowed by the policy. This field cannot be defined if the port field is not defined or if the port field is defined as a named (string) port. The endPort must be equal or greater than port.
	EndPort *int `json:"endPort,omitempty" yaml:"endPort,omitempty"`

	// Port represents the port on the given protocol. This can either be a numerical or named port on a pod. If this field is not provided, this matches all port names and numbers. If present, only traffic on the specified protocol AND port will be matched.
	Port *any `json:"port,omitempty" yaml:"port,omitempty"`

	// Protocol represents the protocol (TCP, UDP, or SCTP) which traffic must match. If not specified, this field defaults to TCP.
	Protocol *string `json:"protocol,omitempty" yaml:"protocol,omitempty"`
}

func NewNetworkPolicyPort() *NetworkPolicyPort {
	return &NetworkPolicyPort{}
}

func NewNetworkPolicyPortWithSpec(spec *NetworkPolicyPort) *NetworkPolicyPort {
	
	return spec
}

func RegisterNetworkPolicyPort(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[NetworkPolicyPort]()).JsNamespace("k8s.networking.v1").Fields(
		js.Field("EndPort"),
		js.Field("Port"),
		js.Field("Protocol"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewNetworkPolicyPort)),
		js.Constructor(reflect.ValueOf(NewNetworkPolicyPortWithSpec)),
	)
}