// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewNetworkPolicy(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "v1")
	document.Set("kind", "NetworkPolicy")
	return document
}

func NewNetworkPolicyWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "v1")
	document.Set("kind", "NetworkPolicy")
	return document
}

func RegisterNetworkPolicy(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewNetworkPolicy)).JsNamespace("k8s.networking.v1").JsName("NetworkPolicy")
	jsRuntime.Constructor(reflect.ValueOf(NewNetworkPolicyWithSpec)).JsNamespace("k8s.networking.v1").JsName("NetworkPolicy")
	
	jsRuntime.Constructor(reflect.ValueOf(NewNetworkPolicy)).JsNamespace("k8s").JsName("NetworkPolicy")
	jsRuntime.Constructor(reflect.ValueOf(NewNetworkPolicyWithSpec)).JsNamespace("k8s").JsName("NetworkPolicy")
	
}