// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewServiceCIDR(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "v1")
	document.Set("kind", "ServiceCIDR")
	return document
}

func NewServiceCIDRWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "v1")
	document.Set("kind", "ServiceCIDR")
	return document
}

func RegisterServiceCIDR(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewServiceCIDR)).JsModule("k8s/networking/v1").JsName("ServiceCIDR")
	jsRuntime.Constructor(reflect.ValueOf(NewServiceCIDRWithSpec)).JsModule("k8s/networking/v1").JsName("ServiceCIDR")
	
	jsRuntime.Constructor(reflect.ValueOf(NewServiceCIDR)).JsModule("k8s").JsName("ServiceCIDR")
	jsRuntime.Constructor(reflect.ValueOf(NewServiceCIDRWithSpec)).JsModule("k8s").JsName("ServiceCIDR")
	
}