// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
)

// Configuration of a horizontal pod autoscaler.
type HorizontalPodAutoscaler struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty" yaml:"apiVersion,omitempty"`

	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`

	// Standard object metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *apimachinerymetav1.ObjectMeta `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	// Spec defines the behaviour of autoscaler. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
	Spec *HorizontalPodAutoscalerSpec `json:"spec,omitempty" yaml:"spec,omitempty"`

	// Status is the current information about the autoscaler.
	Status *HorizontalPodAutoscalerStatus `json:"status,omitempty" yaml:"status,omitempty"`
}

func NewHorizontalPodAutoscaler() *HorizontalPodAutoscaler {
	return &HorizontalPodAutoscaler{}
}

func NewHorizontalPodAutoscalerWithSpec(spec *HorizontalPodAutoscaler) *HorizontalPodAutoscaler {
	version := "v1"
	kind := "HorizontalPodAutoscaler"
	
	spec.ApiVersion = &version
	spec.Kind = &kind
	return spec
}

func RegisterHorizontalPodAutoscaler(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[HorizontalPodAutoscaler]()).JsNamespace("k8s.autoscaling.v1").Fields(
		js.Field("ApiVersion"),
		js.Field("Kind"),
		js.Field("Metadata"),
		js.Field("Spec"),
		js.Field("Status"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewHorizontalPodAutoscaler)),
		js.Constructor(reflect.ValueOf(NewHorizontalPodAutoscalerWithSpec)),
	)
}