// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
)

// List of horizontal pod autoscaler objects.
type HorizontalPodAutoscalerList struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty" yaml:"apiVersion,omitempty"`

	// Items is the list of horizontal pod autoscaler objects.
	Items []*HorizontalPodAutoscaler `json:"items" yaml:"items"`

	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`

	// Standard list metadata.
	Metadata *apimachinerymetav1.ListMeta `json:"metadata,omitempty" yaml:"metadata,omitempty"`
}

func NewHorizontalPodAutoscalerList() *HorizontalPodAutoscalerList {
	return &HorizontalPodAutoscalerList{}
}

func NewHorizontalPodAutoscalerListWithSpec(spec *HorizontalPodAutoscalerList) *HorizontalPodAutoscalerList {
	version := "v1"
	kind := "HorizontalPodAutoscalerList"
	
	spec.ApiVersion = &version
	spec.Kind = &kind
	return spec
}

func RegisterHorizontalPodAutoscalerList(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[HorizontalPodAutoscalerList]()).JsNamespace("k8s.autoscaling.v1").Fields(
		js.Field("ApiVersion"),
		js.Field("Items"),
		js.Field("Kind"),
		js.Field("Metadata"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewHorizontalPodAutoscalerList)),
		js.Constructor(reflect.ValueOf(NewHorizontalPodAutoscalerListWithSpec)),
	)
}