// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// ScaleStatus represents the current status of a scale subresource.
type ScaleStatus struct {
	// Replicas is the actual number of observed instances of the scaled object.
	Replicas int `json:"replicas" yaml:"replicas"`

	// Selector is the label query over pods that should match the replicas count. This is same as the label selector but in the string format to avoid introspection by clients. The string will be in the same format as the query-param syntax. More info about label selectors: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
	Selector *string `json:"selector,omitempty" yaml:"selector,omitempty"`
}

func NewScaleStatus() *ScaleStatus {
	return &ScaleStatus{}
}

func NewScaleStatusWithSpec(spec *ScaleStatus) *ScaleStatus {
	
	return spec
}

func RegisterScaleStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ScaleStatus]()).JsNamespace("k8s.autoscaling.v1").Fields(
		js.Field("Replicas"),
		js.Field("Selector"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewScaleStatus)),
		js.Constructor(reflect.ValueOf(NewScaleStatusWithSpec)),
	)
}