// Code generated by types_generator.go; DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
)

// Storage version of a specific resource.
type StorageVersion struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty" yaml:"apiVersion,omitempty"`

	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`

	// The name is <group>.<resource>.
	Metadata *apimachinerymetav1.ObjectMeta `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	// Spec is an empty spec. It is here to comply with Kubernetes API style.
	Spec *StorageVersionSpec `json:"spec" yaml:"spec"`

	// API server instances report the version they can decode and the version they encode objects to when persisting objects in the backend.
	Status *StorageVersionStatus `json:"status" yaml:"status"`
}

func NewStorageVersion() *StorageVersion {
	return &StorageVersion{}
}

func NewStorageVersionWithSpec(spec *StorageVersion) *StorageVersion {
	version := "v1alpha1"
	kind := "StorageVersion"
	
	spec.ApiVersion = &version
	spec.Kind = &kind
	return spec
}

func RegisterStorageVersion(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[StorageVersion]()).JsNamespace("k8s.apiserverinternal.v1alpha1").Fields(
		js.Field("ApiVersion"),
		js.Field("Kind"),
		js.Field("Metadata"),
		js.Field("Spec"),
		js.Field("Status"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewStorageVersion)),
		js.Constructor(reflect.ValueOf(NewStorageVersionWithSpec)),
	)
}