// Code generated by types_generator.go; DO NOT EDIT.

package v2

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// ContainerResourceMetricSource indicates how to scale on a resource metric known to Kubernetes, as specified in requests and limits, describing each pod in the current scale target (e.g. CPU or memory).  The values will be averaged together before being compared to the target.  Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the "pods" source.  Only one "target" type should be set.
type ContainerResourceMetricSource struct {
	// Container is the name of the container in the pods of the scaling target
	Container string `json:"container" yaml:"container"`

	// Name is the name of the resource in question.
	Name string `json:"name" yaml:"name"`

	// Target specifies the target value for the given metric
	Target *MetricTarget `json:"target" yaml:"target"`
}

func NewContainerResourceMetricSource() *ContainerResourceMetricSource {
	return &ContainerResourceMetricSource{}
}

func NewContainerResourceMetricSourceWithSpec(spec *ContainerResourceMetricSource) *ContainerResourceMetricSource {
	
	return spec
}

func RegisterContainerResourceMetricSource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ContainerResourceMetricSource]()).JsNamespace("k8s.autoscaling.v2").Fields(
		js.Field("Container"),
		js.Field("Name"),
		js.Field("Target"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewContainerResourceMetricSource)),
		js.Constructor(reflect.ValueOf(NewContainerResourceMetricSourceWithSpec)),
	)
}