// Code generated by types_generator.go; DO NOT EDIT.

package v2

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewHorizontalPodAutoscaler(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "v2")
	document.Set("kind", "HorizontalPodAutoscaler")
	return document
}

func NewHorizontalPodAutoscalerWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "v2")
	document.Set("kind", "HorizontalPodAutoscaler")
	return document
}

func RegisterHorizontalPodAutoscaler(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewHorizontalPodAutoscaler)).JsNamespace("k8s.autoscaling.v2").JsName("HorizontalPodAutoscaler")
	jsRuntime.Constructor(reflect.ValueOf(NewHorizontalPodAutoscalerWithSpec)).JsNamespace("k8s.autoscaling.v2").JsName("HorizontalPodAutoscaler")
	
	jsRuntime.Constructor(reflect.ValueOf(NewHorizontalPodAutoscaler)).JsNamespace("k8s").JsName("HorizontalPodAutoscaler")
	jsRuntime.Constructor(reflect.ValueOf(NewHorizontalPodAutoscalerWithSpec)).JsNamespace("k8s").JsName("HorizontalPodAutoscaler")
	
}