// Code generated by types_generator.go; DO NOT EDIT.

package v2

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
)

// MetricIdentifier defines the name and optionally selector for a metric
type MetricIdentifier struct {
	// Name is the name of the given metric
	Name string `json:"name" yaml:"name"`

	// Selector is the string-encoded form of a standard kubernetes label selector for the given metric When set, it is passed as an additional parameter to the metrics server for more specific metrics scoping. When unset, just the metricName will be used to gather metrics.
	Selector *apimachinerymetav1.LabelSelector `json:"selector,omitempty" yaml:"selector,omitempty"`
}

func NewMetricIdentifier() *MetricIdentifier {
	return &MetricIdentifier{}
}

func NewMetricIdentifierWithSpec(spec *MetricIdentifier) *MetricIdentifier {
	
	return spec
}

func RegisterMetricIdentifier(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[MetricIdentifier]()).JsNamespace("k8s.autoscaling.v2").Fields(
		js.Field("Name"),
		js.Field("Selector"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewMetricIdentifier)),
		js.Constructor(reflect.ValueOf(NewMetricIdentifierWithSpec)),
	)
}