// Code generated by types_generator.go; DO NOT EDIT.

package v2

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// MetricValueStatus holds the current value for a metric
type MetricValueStatus struct {
	// CurrentAverageUtilization is the current value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods.
	AverageUtilization *int `json:"averageUtilization,omitempty" yaml:"averageUtilization,omitempty"`

	// AverageValue is the current value of the average of the metric across all relevant pods (as a quantity)
	AverageValue any `json:"averageValue,omitempty" yaml:"averageValue,omitempty"`

	// Value is the current value of the metric (as a quantity).
	Value any `json:"value,omitempty" yaml:"value,omitempty"`
}

func NewMetricValueStatus() *MetricValueStatus {
	return &MetricValueStatus{}
}

func NewMetricValueStatusWithSpec(spec *MetricValueStatus) *MetricValueStatus {
	
	return spec
}

func RegisterMetricValueStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[MetricValueStatus]()).JsNamespace("k8s.autoscaling.v2").Fields(
		js.Field("AverageUtilization"),
		js.Field("AverageValue"),
		js.Field("Value"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewMetricValueStatus)),
		js.Constructor(reflect.ValueOf(NewMetricValueStatusWithSpec)),
	)
}