// Code generated by types_generator.go; DO NOT EDIT.

package v2

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// ObjectMetricSource indicates how to scale on a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
type ObjectMetricSource struct {
	// DescribedObject specifies the descriptions of a object,such as kind,name apiVersion
	DescribedObject *CrossVersionObjectReference `json:"describedObject" yaml:"describedObject"`

	// Metric identifies the target metric by name and selector
	Metric *MetricIdentifier `json:"metric" yaml:"metric"`

	// Target specifies the target value for the given metric
	Target *MetricTarget `json:"target" yaml:"target"`
}

func NewObjectMetricSource() *ObjectMetricSource {
	return &ObjectMetricSource{}
}

func NewObjectMetricSourceWithSpec(spec *ObjectMetricSource) *ObjectMetricSource {
	
	return spec
}

func RegisterObjectMetricSource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ObjectMetricSource]()).JsNamespace("k8s.autoscaling.v2").Fields(
		js.Field("DescribedObject"),
		js.Field("Metric"),
		js.Field("Target"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewObjectMetricSource)),
		js.Constructor(reflect.ValueOf(NewObjectMetricSourceWithSpec)),
	)
}