// Code generated by types_generator.go; DO NOT EDIT.

package v2

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
type ObjectMetricStatus struct {
	// Current contains the current value for the given metric
	Current *MetricValueStatus `json:"current" yaml:"current"`

	// DescribedObject specifies the descriptions of a object,such as kind,name apiVersion
	DescribedObject *CrossVersionObjectReference `json:"describedObject" yaml:"describedObject"`

	// Metric identifies the target metric by name and selector
	Metric *MetricIdentifier `json:"metric" yaml:"metric"`
}

func NewObjectMetricStatus() *ObjectMetricStatus {
	return &ObjectMetricStatus{}
}

func NewObjectMetricStatusWithSpec(spec *ObjectMetricStatus) *ObjectMetricStatus {
	
	return spec
}

func RegisterObjectMetricStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ObjectMetricStatus]()).JsNamespace("k8s.autoscaling.v2").Fields(
		js.Field("Current"),
		js.Field("DescribedObject"),
		js.Field("Metric"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewObjectMetricStatus)),
		js.Constructor(reflect.ValueOf(NewObjectMetricStatusWithSpec)),
	)
}