// Code generated by types_generator.go; DO NOT EDIT.

package v2

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// PodsMetricSource indicates how to scale on a metric describing each pod in the current scale target (for example, transactions-processed-per-second). The values will be averaged together before being compared to the target value.
type PodsMetricSource struct {
	// Metric identifies the target metric by name and selector
	Metric *MetricIdentifier `json:"metric" yaml:"metric"`

	// Target specifies the target value for the given metric
	Target *MetricTarget `json:"target" yaml:"target"`
}

func NewPodsMetricSource() *PodsMetricSource {
	return &PodsMetricSource{}
}

func NewPodsMetricSourceWithSpec(spec *PodsMetricSource) *PodsMetricSource {
	
	return spec
}

func RegisterPodsMetricSource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[PodsMetricSource]()).JsNamespace("k8s.autoscaling.v2").Fields(
		js.Field("Metric"),
		js.Field("Target"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewPodsMetricSource)),
		js.Constructor(reflect.ValueOf(NewPodsMetricSourceWithSpec)),
	)
}