// Code generated by types_generator.go; DO NOT EDIT.

package v2

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// PodsMetricStatus indicates the current value of a metric describing each pod in the current scale target (for example, transactions-processed-per-second).
type PodsMetricStatus struct {
	// Current contains the current value for the given metric
	Current *MetricValueStatus `json:"current" yaml:"current"`

	// Metric identifies the target metric by name and selector
	Metric *MetricIdentifier `json:"metric" yaml:"metric"`
}

func NewPodsMetricStatus() *PodsMetricStatus {
	return &PodsMetricStatus{}
}

func NewPodsMetricStatusWithSpec(spec *PodsMetricStatus) *PodsMetricStatus {
	
	return spec
}

func RegisterPodsMetricStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[PodsMetricStatus]()).JsNamespace("k8s.autoscaling.v2").Fields(
		js.Field("Current"),
		js.Field("Metric"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewPodsMetricStatus)),
		js.Constructor(reflect.ValueOf(NewPodsMetricStatusWithSpec)),
	)
}