// Code generated by types_generator.go; DO NOT EDIT.

package v2

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// ResourceMetricStatus indicates the current value of a resource metric known to Kubernetes, as specified in requests and limits, describing each pod in the current scale target (e.g. CPU or memory).  Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the "pods" source.
type ResourceMetricStatus struct {
	// Current contains the current value for the given metric
	Current *MetricValueStatus `json:"current" yaml:"current"`

	// Name is the name of the resource in question.
	Name string `json:"name" yaml:"name"`
}

func NewResourceMetricStatus() *ResourceMetricStatus {
	return &ResourceMetricStatus{}
}

func NewResourceMetricStatusWithSpec(spec *ResourceMetricStatus) *ResourceMetricStatus {
	
	return spec
}

func RegisterResourceMetricStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ResourceMetricStatus]()).JsNamespace("k8s.autoscaling.v2").Fields(
		js.Field("Current"),
		js.Field("Name"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewResourceMetricStatus)),
		js.Constructor(reflect.ValueOf(NewResourceMetricStatusWithSpec)),
	)
}