// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// DaemonSetUpdateStrategy is a struct used to control the update strategy for a DaemonSet.
type DaemonSetUpdateStrategy struct {
	// Rolling update config params. Present only if type = "RollingUpdate".
	RollingUpdate *RollingUpdateDaemonSet `json:"rollingUpdate,omitempty" yaml:"rollingUpdate,omitempty"`

	// Type of daemon set update. Can be "RollingUpdate" or "OnDelete". Default is RollingUpdate.
	Type *string `json:"type,omitempty" yaml:"type,omitempty"`
}

func NewDaemonSetUpdateStrategy() *DaemonSetUpdateStrategy {
	return &DaemonSetUpdateStrategy{}
}

func NewDaemonSetUpdateStrategyWithSpec(spec *DaemonSetUpdateStrategy) *DaemonSetUpdateStrategy {
	
	return spec
}

func RegisterDaemonSetUpdateStrategy(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[DaemonSetUpdateStrategy]()).JsNamespace("k8s.apps.v1").Fields(
		js.Field("RollingUpdate"),
		js.Field("Type"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewDaemonSetUpdateStrategy)),
		js.Constructor(reflect.ValueOf(NewDaemonSetUpdateStrategyWithSpec)),
	)
}