// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// DeploymentStrategy describes how to replace existing pods with new ones.
type DeploymentStrategy struct {
	// Rolling update config params. Present only if DeploymentStrategyType = RollingUpdate.
	RollingUpdate *RollingUpdateDeployment `json:"rollingUpdate,omitempty" yaml:"rollingUpdate,omitempty"`

	// Type of deployment. Can be "Recreate" or "RollingUpdate". Default is RollingUpdate.
	Type *string `json:"type,omitempty" yaml:"type,omitempty"`
}

func NewDeploymentStrategy() *DeploymentStrategy {
	return &DeploymentStrategy{}
}

func NewDeploymentStrategyWithSpec(spec *DeploymentStrategy) *DeploymentStrategy {
	
	return spec
}

func RegisterDeploymentStrategy(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[DeploymentStrategy]()).JsNamespace("k8s.apps.v1").Fields(
		js.Field("RollingUpdate"),
		js.Field("Type"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewDeploymentStrategy)),
		js.Constructor(reflect.ValueOf(NewDeploymentStrategyWithSpec)),
	)
}