// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
)

// ReplicaSetList is a collection of ReplicaSets.
type ReplicaSetList struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty" yaml:"apiVersion,omitempty"`

	// List of ReplicaSets. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset
	Items []*ReplicaSet `json:"items" yaml:"items"`

	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`

	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *apimachinerymetav1.ListMeta `json:"metadata,omitempty" yaml:"metadata,omitempty"`
}

func NewReplicaSetList() *ReplicaSetList {
	return &ReplicaSetList{}
}

func NewReplicaSetListWithSpec(spec *ReplicaSetList) *ReplicaSetList {
	version := "v1"
	kind := "ReplicaSetList"
	
	spec.ApiVersion = &version
	spec.Kind = &kind
	return spec
}

func RegisterReplicaSetList(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ReplicaSetList]()).JsNamespace("k8s.apps.v1").Fields(
		js.Field("ApiVersion"),
		js.Field("Items"),
		js.Field("Kind"),
		js.Field("Metadata"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewReplicaSetList)),
		js.Constructor(reflect.ValueOf(NewReplicaSetListWithSpec)),
	)
}