// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// ReplicaSetCondition describes the state of a replica set at a certain point.
type ReplicaSetCondition struct {
	// The last time the condition transitioned from one status to another.
	LastTransitionTime *string `json:"lastTransitionTime,omitempty" yaml:"lastTransitionTime,omitempty"`

	// A human readable message indicating details about the transition.
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`

	// The reason for the condition's last transition.
	Reason *string `json:"reason,omitempty" yaml:"reason,omitempty"`

	// Type of replica set condition.
	Type string `json:"type" yaml:"type"`
}

func NewReplicaSetCondition() *ReplicaSetCondition {
	return &ReplicaSetCondition{}
}

func NewReplicaSetConditionWithSpec(spec *ReplicaSetCondition) *ReplicaSetCondition {
	
	return spec
}

func RegisterReplicaSetCondition(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ReplicaSetCondition]()).JsNamespace("k8s.apps.v1").Fields(
		js.Field("LastTransitionTime"),
		js.Field("Message"),
		js.Field("Reason"),
		js.Field("Type"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewReplicaSetCondition)),
		js.Constructor(reflect.ValueOf(NewReplicaSetConditionWithSpec)),
	)
}