// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
	corev1 "github.com/ohayocorp/anemos/pkg/k8s/core/v1"
)

// ReplicaSetSpec is the specification of a ReplicaSet.
type ReplicaSetSpec struct {
	// Minimum number of seconds for which a newly created pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready)
	MinReadySeconds *int `json:"minReadySeconds,omitempty" yaml:"minReadySeconds,omitempty"`

	// Replicas is the number of desired pods. This is a pointer to distinguish between explicit zero and unspecified. Defaults to 1. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset
	Replicas *int `json:"replicas,omitempty" yaml:"replicas,omitempty"`

	// Selector is a label query over pods that should match the replica count. Label keys and values that must match in order to be controlled by this replica set. It must match the pod template's labels. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors
	Selector *apimachinerymetav1.LabelSelector `json:"selector" yaml:"selector"`

	// Template is the object that describes the pod that will be created if insufficient replicas are detected. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#pod-template
	Template *corev1.PodTemplateSpec `json:"template,omitempty" yaml:"template,omitempty"`
}

func NewReplicaSetSpec() *ReplicaSetSpec {
	return &ReplicaSetSpec{}
}

func NewReplicaSetSpecWithSpec(spec *ReplicaSetSpec) *ReplicaSetSpec {
	
	return spec
}

func RegisterReplicaSetSpec(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ReplicaSetSpec]()).JsNamespace("k8s.apps.v1").Fields(
		js.Field("MinReadySeconds"),
		js.Field("Replicas"),
		js.Field("Selector"),
		js.Field("Template"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewReplicaSetSpec)),
		js.Constructor(reflect.ValueOf(NewReplicaSetSpecWithSpec)),
	)
}