// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
)

// PodDisruptionBudgetStatus represents information about the status of a PodDisruptionBudget. Status may trail the actual state of a system.
type PodDisruptionBudgetStatus struct {
	// Conditions contain conditions for PDB. The disruption controller sets the DisruptionAllowed condition. The following are known values for the reason field (additional reasons could be added in the future): - SyncFailed: The controller encountered an error and wasn't able to compute
	//               the number of allowed disruptions. Therefore no disruptions are
	//               allowed and the status of the condition will be False.
	// - InsufficientPods: The number of pods are either at or below the number
	//                     required by the PodDisruptionBudget. No disruptions are
	//                     allowed and the status of the condition will be False.
	// - SufficientPods: There are more pods than required by the PodDisruptionBudget.
	//                   The condition will be True, and the number of allowed
	//                   disruptions are provided by the disruptionsAllowed property.
	Conditions []*apimachinerymetav1.Condition `json:"conditions,omitempty" yaml:"conditions,omitempty"`

	// Current number of healthy pods
	CurrentHealthy int `json:"currentHealthy" yaml:"currentHealthy"`

	// Minimum desired number of healthy pods
	DesiredHealthy int `json:"desiredHealthy" yaml:"desiredHealthy"`

	// DisruptedPods contains information about pods whose eviction was processed by the API server eviction subresource handler but has not yet been observed by the PodDisruptionBudget controller. A pod will be in this map from the time when the API server processed the eviction request to the time when the pod is seen by PDB controller as having been marked for deletion (or after a timeout). The key in the map is the name of the pod and the value is the time when the API server processed the eviction request. If the deletion didn't occur and a pod is still there it will be removed from the list automatically by PodDisruptionBudget controller after some time. If everything goes smooth this map should be empty for the most of the time. Large number of entries in the map may indicate problems with pod deletions.
	DisruptedPods *any `json:"disruptedPods,omitempty" yaml:"disruptedPods,omitempty"`

	// Number of pod disruptions that are currently allowed.
	DisruptionsAllowed int `json:"disruptionsAllowed" yaml:"disruptionsAllowed"`

	// Total number of pods counted by this disruption budget
	ExpectedPods int `json:"expectedPods" yaml:"expectedPods"`

	// Most recent generation observed when updating this PDB status. DisruptionsAllowed and other status information is valid only if observedGeneration equals to PDB's object generation.
	ObservedGeneration *int `json:"observedGeneration,omitempty" yaml:"observedGeneration,omitempty"`
}

func NewPodDisruptionBudgetStatus() *PodDisruptionBudgetStatus {
	return &PodDisruptionBudgetStatus{}
}

func NewPodDisruptionBudgetStatusWithSpec(spec *PodDisruptionBudgetStatus) *PodDisruptionBudgetStatus {
	
	return spec
}

func RegisterPodDisruptionBudgetStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[PodDisruptionBudgetStatus]()).JsNamespace("k8s.policy.v1").Fields(
		js.Field("Conditions"),
		js.Field("CurrentHealthy"),
		js.Field("DesiredHealthy"),
		js.Field("DisruptedPods"),
		js.Field("DisruptionsAllowed"),
		js.Field("ExpectedPods"),
		js.Field("ObservedGeneration"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewPodDisruptionBudgetStatus)),
		js.Constructor(reflect.ValueOf(NewPodDisruptionBudgetStatusWithSpec)),
	)
}