// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// AppArmorProfile defines a pod or container's AppArmor settings.
type AppArmorProfile struct {
	// LocalhostProfile indicates a profile loaded on the node that should be used. The profile must be preconfigured on the node to work. Must match the loaded name of the profile. Must be set if and only if type is "Localhost".
	LocalhostProfile *string `json:"localhostProfile,omitempty" yaml:"localhostProfile,omitempty"`

	// Type indicates which kind of AppArmor profile will be applied. Valid options are:
	//   Localhost - a profile pre-loaded on the node.
	//   RuntimeDefault - the container runtime's default profile.
	//   Unconfined - no AppArmor enforcement.
	Type string `json:"type" yaml:"type"`
}

func NewAppArmorProfile() *AppArmorProfile {
	return &AppArmorProfile{}
}

func NewAppArmorProfileWithSpec(spec *AppArmorProfile) *AppArmorProfile {
	
	return spec
}

func RegisterAppArmorProfile(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[AppArmorProfile]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("LocalhostProfile"),
		js.Field("Type"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewAppArmorProfile)),
		js.Constructor(reflect.ValueOf(NewAppArmorProfileWithSpec)),
	)
}