// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// AzureFile represents an Azure File Service mount on the host and bind mount to the pod.
type AzureFileVolumeSource struct {
	// ReadOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
	ReadOnly *bool `json:"readOnly,omitempty" yaml:"readOnly,omitempty"`

	// SecretName is the  name of secret that contains Azure Storage Account Name and Key
	SecretName string `json:"secretName" yaml:"secretName"`

	// ShareName is the azure share Name
	ShareName string `json:"shareName" yaml:"shareName"`
}

func NewAzureFileVolumeSource() *AzureFileVolumeSource {
	return &AzureFileVolumeSource{}
}

func NewAzureFileVolumeSourceWithSpec(spec *AzureFileVolumeSource) *AzureFileVolumeSource {
	
	return spec
}

func RegisterAzureFileVolumeSource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[AzureFileVolumeSource]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("ReadOnly"),
		js.Field("SecretName"),
		js.Field("ShareName"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewAzureFileVolumeSource)),
		js.Constructor(reflect.ValueOf(NewAzureFileVolumeSourceWithSpec)),
	)
}