// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// Adds and removes POSIX capabilities from running containers.
type Capabilities struct {
	// Added capabilities
	Add *[]string `json:"add,omitempty" yaml:"add,omitempty"`

	// Removed capabilities
	Drop *[]string `json:"drop,omitempty" yaml:"drop,omitempty"`
}

func NewCapabilities() *Capabilities {
	return &Capabilities{}
}

func NewCapabilitiesWithSpec(spec *Capabilities) *Capabilities {
	
	return spec
}

func RegisterCapabilities(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[Capabilities]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Add"),
		js.Field("Drop"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewCapabilities)),
		js.Constructor(reflect.ValueOf(NewCapabilitiesWithSpec)),
	)
}