// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
)

// ClusterTrustBundleProjection describes how to select a set of ClusterTrustBundle objects and project their contents into the pod filesystem.
type ClusterTrustBundleProjection struct {
	// Select all ClusterTrustBundles that match this label selector.  Only has effect if signerName is set.  Mutually-exclusive with name.  If unset, interpreted as "match nothing".  If set but empty, interpreted as "match everything".
	LabelSelector *apimachinerymetav1.LabelSelector `json:"labelSelector,omitempty" yaml:"labelSelector,omitempty"`

	// Select a single ClusterTrustBundle by object name.  Mutually-exclusive with signerName and labelSelector.
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`

	// If true, don't block pod startup if the referenced ClusterTrustBundle(s) aren't available.  If using name, then the named ClusterTrustBundle is allowed not to exist.  If using signerName, then the combination of signerName and labelSelector is allowed to match zero ClusterTrustBundles.
	Optional *bool `json:"optional,omitempty" yaml:"optional,omitempty"`

	// Relative path from the volume root to write the bundle.
	Path string `json:"path" yaml:"path"`

	// Select all ClusterTrustBundles that match this signer name. Mutually-exclusive with name.  The contents of all selected ClusterTrustBundles will be unified and deduplicated.
	SignerName *string `json:"signerName,omitempty" yaml:"signerName,omitempty"`
}

func NewClusterTrustBundleProjection() *ClusterTrustBundleProjection {
	return &ClusterTrustBundleProjection{}
}

func NewClusterTrustBundleProjectionWithSpec(spec *ClusterTrustBundleProjection) *ClusterTrustBundleProjection {
	
	return spec
}

func RegisterClusterTrustBundleProjection(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ClusterTrustBundleProjection]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("LabelSelector"),
		js.Field("Name"),
		js.Field("Optional"),
		js.Field("Path"),
		js.Field("SignerName"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewClusterTrustBundleProjection)),
		js.Constructor(reflect.ValueOf(NewClusterTrustBundleProjectionWithSpec)),
	)
}