// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
)

// ComponentStatus (and ComponentStatusList) holds the cluster validation info. Deprecated: This API is deprecated in v1.19+
type ComponentStatus struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty" yaml:"apiVersion,omitempty"`

	// List of component conditions observed
	Conditions []*ComponentCondition `json:"conditions,omitempty" yaml:"conditions,omitempty"`

	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`

	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *apimachinerymetav1.ObjectMeta `json:"metadata,omitempty" yaml:"metadata,omitempty"`
}

func NewComponentStatus() *ComponentStatus {
	return &ComponentStatus{}
}

func NewComponentStatusWithSpec(spec *ComponentStatus) *ComponentStatus {
	version := "v1"
	kind := "ComponentStatus"
	
	spec.ApiVersion = &version
	spec.Kind = &kind
	return spec
}

func RegisterComponentStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ComponentStatus]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("ApiVersion"),
		js.Field("Conditions"),
		js.Field("Kind"),
		js.Field("Metadata"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewComponentStatus)),
		js.Constructor(reflect.ValueOf(NewComponentStatusWithSpec)),
	)
}