// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// ConfigMapEnvSource selects a ConfigMap to populate the environment variables with.
// The contents of the target ConfigMap's Data field will represent the key-value pairs as environment variables.
type ConfigMapEnvSource struct {
	// Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`

	// Specify whether the ConfigMap must be defined
	Optional *bool `json:"optional,omitempty" yaml:"optional,omitempty"`
}

func NewConfigMapEnvSource() *ConfigMapEnvSource {
	return &ConfigMapEnvSource{}
}

func NewConfigMapEnvSourceWithSpec(spec *ConfigMapEnvSource) *ConfigMapEnvSource {
	
	return spec
}

func RegisterConfigMapEnvSource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ConfigMapEnvSource]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Name"),
		js.Field("Optional"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewConfigMapEnvSource)),
		js.Constructor(reflect.ValueOf(NewConfigMapEnvSourceWithSpec)),
	)
}