// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewConfigMap(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "v1")
	document.Set("kind", "ConfigMap")
	return document
}

func NewConfigMapWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "v1")
	document.Set("kind", "ConfigMap")
	return document
}

func RegisterConfigMap(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewConfigMap)).JsModule("k8s/core/v1").JsName("ConfigMap")
	jsRuntime.Constructor(reflect.ValueOf(NewConfigMapWithSpec)).JsModule("k8s/core/v1").JsName("ConfigMap")
	
	jsRuntime.Constructor(reflect.ValueOf(NewConfigMap)).JsModule("k8s").JsName("ConfigMap")
	jsRuntime.Constructor(reflect.ValueOf(NewConfigMapWithSpec)).JsModule("k8s").JsName("ConfigMap")
	
}