// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// Adapts a ConfigMap into a volume.
// The contents of the target ConfigMap's Data field will be presented in a volume as files using the keys in the Data field as the file names, unless the items element is populated with specific mappings of keys to paths. ConfigMap volumes support ownership management and SELinux relabeling.
type ConfigMapVolumeSource struct {
	// DefaultMode is optional: mode bits used to set permissions on created files by default. Must be an octal value between 0000 and 0777 or a decimal value between 0 and 511. YAML accepts both octal and decimal values, JSON requires decimal values for mode bits. Defaults to 0644. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
	DefaultMode *int `json:"defaultMode,omitempty" yaml:"defaultMode,omitempty"`

	// Items if unspecified, each key-value pair in the Data field of the referenced ConfigMap will be projected into the volume as a file whose name is the key and content is the value. If specified, the listed keys will be projected into the specified paths, and unlisted keys will not be present. If a key is specified which is not present in the ConfigMap, the volume setup will error unless it is marked optional. Paths must be relative and may not contain the '..' path or start with '..'.
	Items []*KeyToPath `json:"items,omitempty" yaml:"items,omitempty"`

	// Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`

	// Optional specify whether the ConfigMap or its keys must be defined
	Optional *bool `json:"optional,omitempty" yaml:"optional,omitempty"`
}

func NewConfigMapVolumeSource() *ConfigMapVolumeSource {
	return &ConfigMapVolumeSource{}
}

func NewConfigMapVolumeSourceWithSpec(spec *ConfigMapVolumeSource) *ConfigMapVolumeSource {
	
	return spec
}

func RegisterConfigMapVolumeSource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ConfigMapVolumeSource]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("DefaultMode"),
		js.Field("Items"),
		js.Field("Name"),
		js.Field("Optional"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewConfigMapVolumeSource)),
		js.Constructor(reflect.ValueOf(NewConfigMapVolumeSourceWithSpec)),
	)
}