// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// Describe a container image
type ContainerImage struct {
	// Names by which this image is known. e.g. ["kubernetes.example/hyperkube:v1.0.7", "cloud-vendor.registry.example/cloud-vendor/hyperkube:v1.0.7"]
	Names *[]string `json:"names,omitempty" yaml:"names,omitempty"`

	// The size of the image in bytes.
	SizeBytes *int `json:"sizeBytes,omitempty" yaml:"sizeBytes,omitempty"`
}

func NewContainerImage() *ContainerImage {
	return &ContainerImage{}
}

func NewContainerImageWithSpec(spec *ContainerImage) *ContainerImage {
	
	return spec
}

func RegisterContainerImage(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ContainerImage]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Names"),
		js.Field("SizeBytes"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewContainerImage)),
		js.Constructor(reflect.ValueOf(NewContainerImageWithSpec)),
	)
}