// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// Represents storage that is managed by an external CSI volume driver
type CSIPersistentVolumeSource struct {
	// ControllerExpandSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI ControllerExpandVolume call. This field is optional, and may be empty if no secret is required. If the secret object contains more than one secret, all secrets are passed.
	ControllerExpandSecretRef *SecretReference `json:"controllerExpandSecretRef,omitempty" yaml:"controllerExpandSecretRef,omitempty"`

	// ControllerPublishSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI ControllerPublishVolume and ControllerUnpublishVolume calls. This field is optional, and may be empty if no secret is required. If the secret object contains more than one secret, all secrets are passed.
	ControllerPublishSecretRef *SecretReference `json:"controllerPublishSecretRef,omitempty" yaml:"controllerPublishSecretRef,omitempty"`

	// Driver is the name of the driver to use for this volume. Required.
	Driver string `json:"driver" yaml:"driver"`

	// FsType to mount. Must be a filesystem type supported by the host operating system. Ex. "ext4", "xfs", "ntfs".
	FsType *string `json:"fsType,omitempty" yaml:"fsType,omitempty"`

	// NodeExpandSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI NodeExpandVolume call. This field is optional, may be omitted if no secret is required. If the secret object contains more than one secret, all secrets are passed.
	NodeExpandSecretRef *SecretReference `json:"nodeExpandSecretRef,omitempty" yaml:"nodeExpandSecretRef,omitempty"`

	// NodePublishSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI NodePublishVolume and NodeUnpublishVolume calls. This field is optional, and may be empty if no secret is required. If the secret object contains more than one secret, all secrets are passed.
	NodePublishSecretRef *SecretReference `json:"nodePublishSecretRef,omitempty" yaml:"nodePublishSecretRef,omitempty"`

	// NodeStageSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI NodeStageVolume and NodeStageVolume and NodeUnstageVolume calls. This field is optional, and may be empty if no secret is required. If the secret object contains more than one secret, all secrets are passed.
	NodeStageSecretRef *SecretReference `json:"nodeStageSecretRef,omitempty" yaml:"nodeStageSecretRef,omitempty"`

	// ReadOnly value to pass to ControllerPublishVolumeRequest. Defaults to false (read/write).
	ReadOnly *bool `json:"readOnly,omitempty" yaml:"readOnly,omitempty"`

	// VolumeAttributes of the volume to publish.
	VolumeAttributes map[string]string `json:"volumeAttributes,omitempty" yaml:"volumeAttributes,omitempty"`

	// VolumeHandle is the unique volume name returned by the CSI volume plugin’s CreateVolume to refer to the volume on all subsequent calls. Required.
	VolumeHandle string `json:"volumeHandle" yaml:"volumeHandle"`
}

func NewCSIPersistentVolumeSource() *CSIPersistentVolumeSource {
	return &CSIPersistentVolumeSource{}
}

func NewCSIPersistentVolumeSourceWithSpec(spec *CSIPersistentVolumeSource) *CSIPersistentVolumeSource {
	
	return spec
}

func RegisterCSIPersistentVolumeSource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[CSIPersistentVolumeSource]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("ControllerExpandSecretRef"),
		js.Field("ControllerPublishSecretRef"),
		js.Field("Driver"),
		js.Field("FsType"),
		js.Field("NodeExpandSecretRef"),
		js.Field("NodePublishSecretRef"),
		js.Field("NodeStageSecretRef"),
		js.Field("ReadOnly"),
		js.Field("VolumeAttributes"),
		js.Field("VolumeHandle"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewCSIPersistentVolumeSource)),
		js.Constructor(reflect.ValueOf(NewCSIPersistentVolumeSourceWithSpec)),
	)
}