// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// Represents downward API info for projecting into a projected volume. Note that this is identical to a downwardAPI volume source without the default mode.
type DownwardAPIProjection struct {
	// Items is a list of DownwardAPIVolume file
	Items []*DownwardAPIVolumeFile `json:"items,omitempty" yaml:"items,omitempty"`
}

func NewDownwardAPIProjection() *DownwardAPIProjection {
	return &DownwardAPIProjection{}
}

func NewDownwardAPIProjectionWithSpec(spec *DownwardAPIProjection) *DownwardAPIProjection {
	
	return spec
}

func RegisterDownwardAPIProjection(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[DownwardAPIProjection]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Items"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewDownwardAPIProjection)),
		js.Constructor(reflect.ValueOf(NewDownwardAPIProjectionWithSpec)),
	)
}