// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// Represents an empty directory for a pod. Empty directory volumes support ownership management and SELinux relabeling.
type EmptyDirVolumeSource struct {
	// Medium represents what type of storage medium should back this directory. The default is "" which means to use the node's default medium. Must be an empty string (default) or Memory. More info: https://kubernetes.io/docs/concepts/storage/volumes#emptydir
	Medium *string `json:"medium,omitempty" yaml:"medium,omitempty"`

	// SizeLimit is the total amount of local storage required for this EmptyDir volume. The size limit is also applicable for memory medium. The maximum usage on memory medium EmptyDir would be the minimum value between the SizeLimit specified here and the sum of memory limits of all containers in a pod. The default is nil which means that the limit is undefined. More info: https://kubernetes.io/docs/concepts/storage/volumes#emptydir
	SizeLimit *any `json:"sizeLimit,omitempty" yaml:"sizeLimit,omitempty"`
}

func NewEmptyDirVolumeSource() *EmptyDirVolumeSource {
	return &EmptyDirVolumeSource{}
}

func NewEmptyDirVolumeSourceWithSpec(spec *EmptyDirVolumeSource) *EmptyDirVolumeSource {
	
	return spec
}

func RegisterEmptyDirVolumeSource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[EmptyDirVolumeSource]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Medium"),
		js.Field("SizeLimit"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewEmptyDirVolumeSource)),
		js.Constructor(reflect.ValueOf(NewEmptyDirVolumeSourceWithSpec)),
	)
}