// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// FlexVolume represents a generic volume resource that is provisioned/attached using an exec based plugin.
type FlexVolumeSource struct {
	// Driver is the name of the driver to use for this volume.
	Driver string `json:"driver" yaml:"driver"`

	// FsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. "ext4", "xfs", "ntfs". The default filesystem depends on FlexVolume script.
	FsType *string `json:"fsType,omitempty" yaml:"fsType,omitempty"`

	// Options is Optional: this field holds extra command options if any.
	Options *any `json:"options,omitempty" yaml:"options,omitempty"`

	// ReadOnly is Optional: defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
	ReadOnly *bool `json:"readOnly,omitempty" yaml:"readOnly,omitempty"`

	// SecretRef is Optional: secretRef is reference to the secret object containing sensitive information to pass to the plugin scripts. This may be empty if no secret object is specified. If the secret object contains more than one secret, all secrets are passed to the plugin scripts.
	SecretRef *LocalObjectReference `json:"secretRef,omitempty" yaml:"secretRef,omitempty"`
}

func NewFlexVolumeSource() *FlexVolumeSource {
	return &FlexVolumeSource{}
}

func NewFlexVolumeSourceWithSpec(spec *FlexVolumeSource) *FlexVolumeSource {
	
	return spec
}

func RegisterFlexVolumeSource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[FlexVolumeSource]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Driver"),
		js.Field("FsType"),
		js.Field("Options"),
		js.Field("ReadOnly"),
		js.Field("SecretRef"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewFlexVolumeSource)),
		js.Constructor(reflect.ValueOf(NewFlexVolumeSourceWithSpec)),
	)
}