// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// Represents a Glusterfs mount that lasts the lifetime of a pod. Glusterfs volumes do not support ownership management or SELinux relabeling.
type GlusterfsVolumeSource struct {
	// Endpoints is the endpoint name that details Glusterfs topology.
	Endpoints string `json:"endpoints" yaml:"endpoints"`

	// Path is the Glusterfs volume path. More info: https://examples.k8s.io/volumes/glusterfs/README.md#create-a-pod
	Path string `json:"path" yaml:"path"`

	// ReadOnly here will force the Glusterfs volume to be mounted with read-only permissions. Defaults to false. More info: https://examples.k8s.io/volumes/glusterfs/README.md#create-a-pod
	ReadOnly *bool `json:"readOnly,omitempty" yaml:"readOnly,omitempty"`
}

func NewGlusterfsVolumeSource() *GlusterfsVolumeSource {
	return &GlusterfsVolumeSource{}
}

func NewGlusterfsVolumeSourceWithSpec(spec *GlusterfsVolumeSource) *GlusterfsVolumeSource {
	
	return spec
}

func RegisterGlusterfsVolumeSource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[GlusterfsVolumeSource]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Endpoints"),
		js.Field("Path"),
		js.Field("ReadOnly"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewGlusterfsVolumeSource)),
		js.Constructor(reflect.ValueOf(NewGlusterfsVolumeSourceWithSpec)),
	)
}