// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// Represents a Glusterfs mount that lasts the lifetime of a pod. Glusterfs volumes do not support ownership management or SELinux relabeling.
type GlusterfsPersistentVolumeSource struct {
	// Endpoints is the endpoint name that details Glusterfs topology. More info: https://examples.k8s.io/volumes/glusterfs/README.md#create-a-pod
	Endpoints string `json:"endpoints" yaml:"endpoints"`

	// EndpointsNamespace is the namespace that contains Glusterfs endpoint. If this field is empty, the EndpointNamespace defaults to the same namespace as the bound PVC. More info: https://examples.k8s.io/volumes/glusterfs/README.md#create-a-pod
	EndpointsNamespace *string `json:"endpointsNamespace,omitempty" yaml:"endpointsNamespace,omitempty"`

	// Path is the Glusterfs volume path. More info: https://examples.k8s.io/volumes/glusterfs/README.md#create-a-pod
	Path string `json:"path" yaml:"path"`

	// ReadOnly here will force the Glusterfs volume to be mounted with read-only permissions. Defaults to false. More info: https://examples.k8s.io/volumes/glusterfs/README.md#create-a-pod
	ReadOnly *bool `json:"readOnly,omitempty" yaml:"readOnly,omitempty"`
}

func NewGlusterfsPersistentVolumeSource() *GlusterfsPersistentVolumeSource {
	return &GlusterfsPersistentVolumeSource{}
}

func NewGlusterfsPersistentVolumeSourceWithSpec(spec *GlusterfsPersistentVolumeSource) *GlusterfsPersistentVolumeSource {
	
	return spec
}

func RegisterGlusterfsPersistentVolumeSource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[GlusterfsPersistentVolumeSource]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Endpoints"),
		js.Field("EndpointsNamespace"),
		js.Field("Path"),
		js.Field("ReadOnly"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewGlusterfsPersistentVolumeSource)),
		js.Constructor(reflect.ValueOf(NewGlusterfsPersistentVolumeSourceWithSpec)),
	)
}