// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// LoadBalancerIngress represents the status of a load-balancer ingress point: traffic intended for the service should be sent to an ingress point.
type LoadBalancerIngress struct {
	// Hostname is set for load-balancer ingress points that are DNS based (typically AWS load-balancers)
	Hostname *string `json:"hostname,omitempty" yaml:"hostname,omitempty"`

	// IP is set for load-balancer ingress points that are IP based (typically GCE or OpenStack load-balancers)
	Ip *string `json:"ip,omitempty" yaml:"ip,omitempty"`

	// IPMode specifies how the load-balancer IP behaves, and may only be specified when the ip field is specified. Setting this to "VIP" indicates that traffic is delivered to the node with the destination set to the load-balancer's IP and port. Setting this to "Proxy" indicates that traffic is delivered to the node or pod with the destination set to the node's IP and node port or the pod's IP and port. Service implementations may use this information to adjust traffic routing.
	IpMode *string `json:"ipMode,omitempty" yaml:"ipMode,omitempty"`

	// Ports is a list of records of service ports If used, every port defined in the service should have an entry in it
	Ports []*PortStatus `json:"ports,omitempty" yaml:"ports,omitempty"`
}

func NewLoadBalancerIngress() *LoadBalancerIngress {
	return &LoadBalancerIngress{}
}

func NewLoadBalancerIngressWithSpec(spec *LoadBalancerIngress) *LoadBalancerIngress {
	
	return spec
}

func RegisterLoadBalancerIngress(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[LoadBalancerIngress]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Hostname"),
		js.Field("Ip"),
		js.Field("IpMode"),
		js.Field("Ports"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewLoadBalancerIngress)),
		js.Constructor(reflect.ValueOf(NewLoadBalancerIngressWithSpec)),
	)
}