// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// Local represents directly-attached storage with node affinity
type LocalVolumeSource struct {
	// FsType is the filesystem type to mount. It applies only when the Path is a block device. Must be a filesystem type supported by the host operating system. Ex. "ext4", "xfs", "ntfs". The default value is to auto-select a filesystem if unspecified.
	FsType *string `json:"fsType,omitempty" yaml:"fsType,omitempty"`

	// Path of the full path to the volume on the node. It can be either a directory or block device (disk, partition, ...).
	Path string `json:"path" yaml:"path"`
}

func NewLocalVolumeSource() *LocalVolumeSource {
	return &LocalVolumeSource{}
}

func NewLocalVolumeSourceWithSpec(spec *LocalVolumeSource) *LocalVolumeSource {
	
	return spec
}

func RegisterLocalVolumeSource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[LocalVolumeSource]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("FsType"),
		js.Field("Path"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewLocalVolumeSource)),
		js.Constructor(reflect.ValueOf(NewLocalVolumeSourceWithSpec)),
	)
}