// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// NamespaceStatus is information about the current status of a Namespace.
type NamespaceStatus struct {
	// Represents the latest available observations of a namespace's current state.
	Conditions []*NamespaceCondition `json:"conditions,omitempty" yaml:"conditions,omitempty"`

	// Phase is the current lifecycle phase of the namespace. More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/
	Phase *string `json:"phase,omitempty" yaml:"phase,omitempty"`
}

func NewNamespaceStatus() *NamespaceStatus {
	return &NamespaceStatus{}
}

func NewNamespaceStatusWithSpec(spec *NamespaceStatus) *NamespaceStatus {
	
	return spec
}

func RegisterNamespaceStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[NamespaceStatus]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Conditions"),
		js.Field("Phase"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewNamespaceStatus)),
		js.Constructor(reflect.ValueOf(NewNamespaceStatusWithSpec)),
	)
}