// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewNamespace(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "v1")
	document.Set("kind", "Namespace")
	return document
}

func NewNamespaceWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "v1")
	document.Set("kind", "Namespace")
	return document
}

func RegisterNamespace(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewNamespace)).JsModule("k8s/core/v1").JsName("Namespace")
	jsRuntime.Constructor(reflect.ValueOf(NewNamespaceWithSpec)).JsModule("k8s/core/v1").JsName("Namespace")
	
	jsRuntime.Constructor(reflect.ValueOf(NewNamespace)).JsModule("k8s").JsName("Namespace")
	jsRuntime.Constructor(reflect.ValueOf(NewNamespaceWithSpec)).JsModule("k8s").JsName("Namespace")
	
}