// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// A node selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
type NodeSelectorRequirement struct {
	// The label key that the selector applies to.
	Key string `json:"key" yaml:"key"`

	// Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
	Operator string `json:"operator" yaml:"operator"`

	// An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.
	Values *[]string `json:"values,omitempty" yaml:"values,omitempty"`
}

func NewNodeSelectorRequirement() *NodeSelectorRequirement {
	return &NodeSelectorRequirement{}
}

func NewNodeSelectorRequirementWithSpec(spec *NodeSelectorRequirement) *NodeSelectorRequirement {
	
	return spec
}

func RegisterNodeSelectorRequirement(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[NodeSelectorRequirement]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Key"),
		js.Field("Operator"),
		js.Field("Values"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewNodeSelectorRequirement)),
		js.Constructor(reflect.ValueOf(NewNodeSelectorRequirementWithSpec)),
	)
}