// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// NodeDaemonEndpoints lists ports opened by daemons running on the Node.
type NodeDaemonEndpoints struct {
	// Endpoint on which Kubelet is listening.
	KubeletEndpoint *DaemonEndpoint `json:"kubeletEndpoint,omitempty" yaml:"kubeletEndpoint,omitempty"`
}

func NewNodeDaemonEndpoints() *NodeDaemonEndpoints {
	return &NodeDaemonEndpoints{}
}

func NewNodeDaemonEndpointsWithSpec(spec *NodeDaemonEndpoints) *NodeDaemonEndpoints {
	
	return spec
}

func RegisterNodeDaemonEndpoints(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[NodeDaemonEndpoints]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("KubeletEndpoint"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewNodeDaemonEndpoints)),
		js.Constructor(reflect.ValueOf(NewNodeDaemonEndpointsWithSpec)),
	)
}