// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// NodeRuntimeHandlerFeatures is a set of features implemented by the runtime handler.
type NodeRuntimeHandlerFeatures struct {
	// RecursiveReadOnlyMounts is set to true if the runtime handler supports RecursiveReadOnlyMounts.
	RecursiveReadOnlyMounts *bool `json:"recursiveReadOnlyMounts,omitempty" yaml:"recursiveReadOnlyMounts,omitempty"`

	// UserNamespaces is set to true if the runtime handler supports UserNamespaces, including for volumes.
	UserNamespaces *bool `json:"userNamespaces,omitempty" yaml:"userNamespaces,omitempty"`
}

func NewNodeRuntimeHandlerFeatures() *NodeRuntimeHandlerFeatures {
	return &NodeRuntimeHandlerFeatures{}
}

func NewNodeRuntimeHandlerFeaturesWithSpec(spec *NodeRuntimeHandlerFeatures) *NodeRuntimeHandlerFeatures {
	
	return spec
}

func RegisterNodeRuntimeHandlerFeatures(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[NodeRuntimeHandlerFeatures]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("RecursiveReadOnlyMounts"),
		js.Field("UserNamespaces"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewNodeRuntimeHandlerFeatures)),
		js.Constructor(reflect.ValueOf(NewNodeRuntimeHandlerFeaturesWithSpec)),
	)
}