// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// NodeRuntimeHandler is a set of runtime handler information.
type NodeRuntimeHandler struct {
	// Supported features.
	Features *NodeRuntimeHandlerFeatures `json:"features,omitempty" yaml:"features,omitempty"`

	// Runtime handler name. Empty for the default runtime handler.
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`
}

func NewNodeRuntimeHandler() *NodeRuntimeHandler {
	return &NodeRuntimeHandler{}
}

func NewNodeRuntimeHandlerWithSpec(spec *NodeRuntimeHandler) *NodeRuntimeHandler {
	
	return spec
}

func RegisterNodeRuntimeHandler(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[NodeRuntimeHandler]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Features"),
		js.Field("Name"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewNodeRuntimeHandler)),
		js.Constructor(reflect.ValueOf(NewNodeRuntimeHandlerWithSpec)),
	)
}