// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// NodeFeatures describes the set of features implemented by the CRI implementation. The features contained in the NodeFeatures should depend only on the cri implementation independent of runtime handlers.
type NodeFeatures struct {
	// SupplementalGroupsPolicy is set to true if the runtime supports SupplementalGroupsPolicy and ContainerUser.
	SupplementalGroupsPolicy *bool `json:"supplementalGroupsPolicy,omitempty" yaml:"supplementalGroupsPolicy,omitempty"`
}

func NewNodeFeatures() *NodeFeatures {
	return &NodeFeatures{}
}

func NewNodeFeaturesWithSpec(spec *NodeFeatures) *NodeFeatures {
	
	return spec
}

func RegisterNodeFeatures(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[NodeFeatures]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("SupplementalGroupsPolicy"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewNodeFeatures)),
		js.Constructor(reflect.ValueOf(NewNodeFeaturesWithSpec)),
	)
}