// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// NodeSpec describes the attributes that a node is created with.
type NodeSpec struct {
	// Deprecated: Previously used to specify the source of the node's configuration for the DynamicKubeletConfig feature. This feature is removed.
	ConfigSource *NodeConfigSource `json:"configSource,omitempty" yaml:"configSource,omitempty"`

	// Deprecated. Not all kubelets will set this field. Remove field after 1.13. see: https://issues.k8s.io/61966
	ExternalID *string `json:"externalID,omitempty" yaml:"externalID,omitempty"`

	// PodCIDR represents the pod IP range assigned to the node.
	PodCIDR *string `json:"podCIDR,omitempty" yaml:"podCIDR,omitempty"`

	// PodCIDRs represents the IP ranges assigned to the node for usage by Pods on that node. If this field is specified, the 0th entry must match the podCIDR field. It may contain at most 1 value for each of IPv4 and IPv6.
	PodCIDRs *[]string `json:"podCIDRs,omitempty" yaml:"podCIDRs,omitempty"`

	// ID of the node assigned by the cloud provider in the format: <ProviderName>://<ProviderSpecificNodeID>
	ProviderID *string `json:"providerID,omitempty" yaml:"providerID,omitempty"`

	// If specified, the node's taints.
	Taints []*Taint `json:"taints,omitempty" yaml:"taints,omitempty"`

	// Unschedulable controls node schedulability of new pods. By default, node is schedulable. More info: https://kubernetes.io/docs/concepts/nodes/node/#manual-node-administration
	Unschedulable *bool `json:"unschedulable,omitempty" yaml:"unschedulable,omitempty"`
}

func NewNodeSpec() *NodeSpec {
	return &NodeSpec{}
}

func NewNodeSpecWithSpec(spec *NodeSpec) *NodeSpec {
	
	return spec
}

func RegisterNodeSpec(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[NodeSpec]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("ConfigSource"),
		js.Field("ExternalID"),
		js.Field("PodCIDR"),
		js.Field("PodCIDRs"),
		js.Field("ProviderID"),
		js.Field("Taints"),
		js.Field("Unschedulable"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewNodeSpec)),
		js.Constructor(reflect.ValueOf(NewNodeSpecWithSpec)),
	)
}