// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// ObjectFieldSelector selects an APIVersioned field of an object.
type ObjectFieldSelector struct {
	// Version of the schema the FieldPath is written in terms of, defaults to "v1".
	ApiVersion *string `json:"apiVersion,omitempty" yaml:"apiVersion,omitempty"`

	// Path of the field to select in the specified API version.
	FieldPath string `json:"fieldPath" yaml:"fieldPath"`
}

func NewObjectFieldSelector() *ObjectFieldSelector {
	return &ObjectFieldSelector{}
}

func NewObjectFieldSelectorWithSpec(spec *ObjectFieldSelector) *ObjectFieldSelector {
	
	return spec
}

func RegisterObjectFieldSelector(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ObjectFieldSelector]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("ApiVersion"),
		js.Field("FieldPath"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewObjectFieldSelector)),
		js.Constructor(reflect.ValueOf(NewObjectFieldSelectorWithSpec)),
	)
}