// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// PersistentVolumeClaimStatus is the current status of a persistent volume claim.
type PersistentVolumeClaimStatus struct {
	// AccessModes contains the actual access modes the volume backing the PVC has. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
	AccessModes *[]string `json:"accessModes,omitempty" yaml:"accessModes,omitempty"`

	// AllocatedResourceStatuses stores status of resource being resized for the given PVC. Key names follow standard Kubernetes label syntax. Valid values are either:
	// 	* Un-prefixed keys:
	// 		- storage - the capacity of the volume.
	// 	* Custom resources must use implementation-defined prefixed names such as "example.com/my-custom-resource"
	// Apart from above values - keys that are unprefixed or have kubernetes.io prefix are considered reserved and hence may not be used.
	// ClaimResourceStatus can be in any of following states:
	// 	- ControllerResizeInProgress:
	// 		State set when resize controller starts resizing the volume in control-plane.
	// 	- ControllerResizeFailed:
	// 		State set when resize has failed in resize controller with a terminal error.
	// 	- NodeResizePending:
	// 		State set when resize controller has finished resizing the volume but further resizing of
	// 		volume is needed on the node.
	// 	- NodeResizeInProgress:
	// 		State set when kubelet starts resizing the volume.
	// 	- NodeResizeFailed:
	// 		State set when resizing has failed in kubelet with a terminal error. Transient errors don't set
	// 		NodeResizeFailed.
	// For example: if expanding a PVC for more capacity - this field can be one of the following states:
	// 	- pvc.status.allocatedResourceStatus['storage'] = "ControllerResizeInProgress"
	//      - pvc.status.allocatedResourceStatus['storage'] = "ControllerResizeFailed"
	//      - pvc.status.allocatedResourceStatus['storage'] = "NodeResizePending"
	//      - pvc.status.allocatedResourceStatus['storage'] = "NodeResizeInProgress"
	//      - pvc.status.allocatedResourceStatus['storage'] = "NodeResizeFailed"
	// When this field is not set, it means that no resize operation is in progress for the given PVC.
	// A controller that receives PVC update with previously unknown resourceName or ClaimResourceStatus should ignore the update for the purpose it was designed. For example - a controller that only is responsible for resizing capacity of the volume, should ignore PVC updates that change other valid resources associated with PVC.
	// This is an alpha field and requires enabling RecoverVolumeExpansionFailure feature.
	AllocatedResourceStatuses *any `json:"allocatedResourceStatuses,omitempty" yaml:"allocatedResourceStatuses,omitempty"`

	// AllocatedResources tracks the resources allocated to a PVC including its capacity. Key names follow standard Kubernetes label syntax. Valid values are either:
	// 	* Un-prefixed keys:
	// 		- storage - the capacity of the volume.
	// 	* Custom resources must use implementation-defined prefixed names such as "example.com/my-custom-resource"
	// Apart from above values - keys that are unprefixed or have kubernetes.io prefix are considered reserved and hence may not be used.
	// Capacity reported here may be larger than the actual capacity when a volume expansion operation is requested. For storage quota, the larger value from allocatedResources and PVC.spec.resources is used. If allocatedResources is not set, PVC.spec.resources alone is used for quota calculation. If a volume expansion capacity request is lowered, allocatedResources is only lowered if there are no expansion operations in progress and if the actual volume capacity is equal or lower than the requested capacity.
	// A controller that receives PVC update with previously unknown resourceName should ignore the update for the purpose it was designed. For example - a controller that only is responsible for resizing capacity of the volume, should ignore PVC updates that change other valid resources associated with PVC.
	// This is an alpha field and requires enabling RecoverVolumeExpansionFailure feature.
	AllocatedResources *any `json:"allocatedResources,omitempty" yaml:"allocatedResources,omitempty"`

	// Capacity represents the actual resources of the underlying volume.
	Capacity *any `json:"capacity,omitempty" yaml:"capacity,omitempty"`

	// Conditions is the current Condition of persistent volume claim. If underlying persistent volume is being resized then the Condition will be set to 'Resizing'.
	Conditions []*PersistentVolumeClaimCondition `json:"conditions,omitempty" yaml:"conditions,omitempty"`

	// CurrentVolumeAttributesClassName is the current name of the VolumeAttributesClass the PVC is using. When unset, there is no VolumeAttributeClass applied to this PersistentVolumeClaim
	CurrentVolumeAttributesClassName *string `json:"currentVolumeAttributesClassName,omitempty" yaml:"currentVolumeAttributesClassName,omitempty"`

	// ModifyVolumeStatus represents the status object of ControllerModifyVolume operation. When this is unset, there is no ModifyVolume operation being attempted.
	ModifyVolumeStatus *ModifyVolumeStatus `json:"modifyVolumeStatus,omitempty" yaml:"modifyVolumeStatus,omitempty"`

	// Phase represents the current phase of PersistentVolumeClaim.
	Phase *string `json:"phase,omitempty" yaml:"phase,omitempty"`
}

func NewPersistentVolumeClaimStatus() *PersistentVolumeClaimStatus {
	return &PersistentVolumeClaimStatus{}
}

func NewPersistentVolumeClaimStatusWithSpec(spec *PersistentVolumeClaimStatus) *PersistentVolumeClaimStatus {
	
	return spec
}

func RegisterPersistentVolumeClaimStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[PersistentVolumeClaimStatus]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("AccessModes"),
		js.Field("AllocatedResourceStatuses"),
		js.Field("AllocatedResources"),
		js.Field("Capacity"),
		js.Field("Conditions"),
		js.Field("CurrentVolumeAttributesClassName"),
		js.Field("ModifyVolumeStatus"),
		js.Field("Phase"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewPersistentVolumeClaimStatus)),
		js.Constructor(reflect.ValueOf(NewPersistentVolumeClaimStatusWithSpec)),
	)
}