// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewPersistentVolume(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "v1")
	document.Set("kind", "PersistentVolume")
	return document
}

func NewPersistentVolumeWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "v1")
	document.Set("kind", "PersistentVolume")
	return document
}

func RegisterPersistentVolume(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewPersistentVolume)).JsModule("k8s/core/v1").JsName("PersistentVolume")
	jsRuntime.Constructor(reflect.ValueOf(NewPersistentVolumeWithSpec)).JsModule("k8s/core/v1").JsName("PersistentVolume")
	
	jsRuntime.Constructor(reflect.ValueOf(NewPersistentVolume)).JsModule("k8s").JsName("PersistentVolume")
	jsRuntime.Constructor(reflect.ValueOf(NewPersistentVolumeWithSpec)).JsModule("k8s").JsName("PersistentVolume")
	
}