// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// PodOS defines the OS parameters of a pod.
type PodOS struct {
	// Name is the name of the operating system. The currently supported values are linux and windows. Additional value may be defined in future and can be one of: https://github.com/opencontainers/runtime-spec/blob/master/config.md#platform-specific-configuration Clients should expect to handle additional values and treat unrecognized values in this field as os: null
	Name string `json:"name" yaml:"name"`
}

func NewPodOS() *PodOS {
	return &PodOS{}
}

func NewPodOSWithSpec(spec *PodOS) *PodOS {
	
	return spec
}

func RegisterPodOS(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[PodOS]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Name"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewPodOS)),
		js.Constructor(reflect.ValueOf(NewPodOSWithSpec)),
	)
}