// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// PodSchedulingGate is associated to a Pod to guard its scheduling.
type PodSchedulingGate struct {
	// Name of the scheduling gate. Each scheduling gate must have a unique name field.
	Name string `json:"name" yaml:"name"`
}

func NewPodSchedulingGate() *PodSchedulingGate {
	return &PodSchedulingGate{}
}

func NewPodSchedulingGateWithSpec(spec *PodSchedulingGate) *PodSchedulingGate {
	
	return spec
}

func RegisterPodSchedulingGate(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[PodSchedulingGate]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Name"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewPodSchedulingGate)),
		js.Constructor(reflect.ValueOf(NewPodSchedulingGateWithSpec)),
	)
}