// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// An empty preferred scheduling term matches all objects with implicit weight 0 (i.e. it's a no-op). A null preferred scheduling term matches no objects (i.e. is also a no-op).
type PreferredSchedulingTerm struct {
	// A node selector term, associated with the corresponding weight.
	Preference *NodeSelectorTerm `json:"preference" yaml:"preference"`

	// Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
	Weight int `json:"weight" yaml:"weight"`
}

func NewPreferredSchedulingTerm() *PreferredSchedulingTerm {
	return &PreferredSchedulingTerm{}
}

func NewPreferredSchedulingTermWithSpec(spec *PreferredSchedulingTerm) *PreferredSchedulingTerm {
	
	return spec
}

func RegisterPreferredSchedulingTerm(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[PreferredSchedulingTerm]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Preference"),
		js.Field("Weight"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewPreferredSchedulingTerm)),
		js.Constructor(reflect.ValueOf(NewPreferredSchedulingTermWithSpec)),
	)
}