// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewResourceQuota(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "v1")
	document.Set("kind", "ResourceQuota")
	return document
}

func NewResourceQuotaWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "v1")
	document.Set("kind", "ResourceQuota")
	return document
}

func RegisterResourceQuota(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewResourceQuota)).JsModule("k8s/core/v1").JsName("ResourceQuota")
	jsRuntime.Constructor(reflect.ValueOf(NewResourceQuotaWithSpec)).JsModule("k8s/core/v1").JsName("ResourceQuota")
	
	jsRuntime.Constructor(reflect.ValueOf(NewResourceQuota)).JsModule("k8s").JsName("ResourceQuota")
	jsRuntime.Constructor(reflect.ValueOf(NewResourceQuotaWithSpec)).JsModule("k8s").JsName("ResourceQuota")
	
}