// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// SecretKeySelector selects a key of a Secret.
type SecretKeySelector struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key" yaml:"key"`

	// Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`

	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty" yaml:"optional,omitempty"`
}

func NewSecretKeySelector() *SecretKeySelector {
	return &SecretKeySelector{}
}

func NewSecretKeySelectorWithSpec(spec *SecretKeySelector) *SecretKeySelector {
	
	return spec
}

func RegisterSecretKeySelector(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[SecretKeySelector]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Key"),
		js.Field("Name"),
		js.Field("Optional"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewSecretKeySelector)),
		js.Constructor(reflect.ValueOf(NewSecretKeySelectorWithSpec)),
	)
}