// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// SecretEnvSource selects a Secret to populate the environment variables with.
// The contents of the target Secret's Data field will represent the key-value pairs as environment variables.
type SecretEnvSource struct {
	// Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`

	// Specify whether the Secret must be defined
	Optional *bool `json:"optional,omitempty" yaml:"optional,omitempty"`
}

func NewSecretEnvSource() *SecretEnvSource {
	return &SecretEnvSource{}
}

func NewSecretEnvSourceWithSpec(spec *SecretEnvSource) *SecretEnvSource {
	
	return spec
}

func RegisterSecretEnvSource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[SecretEnvSource]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("Name"),
		js.Field("Optional"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewSecretEnvSource)),
		js.Constructor(reflect.ValueOf(NewSecretEnvSourceWithSpec)),
	)
}