// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewService(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "v1")
	document.Set("kind", "Service")
	return document
}

func NewServiceWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "v1")
	document.Set("kind", "Service")
	return document
}

func RegisterService(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewService)).JsNamespace("k8s.core.v1").JsName("Service")
	jsRuntime.Constructor(reflect.ValueOf(NewServiceWithSpec)).JsNamespace("k8s.core.v1").JsName("Service")
	
	jsRuntime.Constructor(reflect.ValueOf(NewService)).JsNamespace("k8s").JsName("Service")
	jsRuntime.Constructor(reflect.ValueOf(NewServiceWithSpec)).JsNamespace("k8s").JsName("Service")
	
}