// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// SessionAffinityConfig represents the configurations of session affinity.
type SessionAffinityConfig struct {
	// ClientIP contains the configurations of Client IP based session affinity.
	ClientIP *ClientIPConfig `json:"clientIP,omitempty" yaml:"clientIP,omitempty"`
}

func NewSessionAffinityConfig() *SessionAffinityConfig {
	return &SessionAffinityConfig{}
}

func NewSessionAffinityConfigWithSpec(spec *SessionAffinityConfig) *SessionAffinityConfig {
	
	return spec
}

func RegisterSessionAffinityConfig(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[SessionAffinityConfig]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("ClientIP"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewSessionAffinityConfig)),
		js.Constructor(reflect.ValueOf(NewSessionAffinityConfigWithSpec)),
	)
}