// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// WindowsSecurityContextOptions contain Windows-specific options and credentials.
type WindowsSecurityContextOptions struct {
	// GMSACredentialSpec is where the GMSA admission webhook (https://github.com/kubernetes-sigs/windows-gmsa) inlines the contents of the GMSA credential spec named by the GMSACredentialSpecName field.
	GmsaCredentialSpec *string `json:"gmsaCredentialSpec,omitempty" yaml:"gmsaCredentialSpec,omitempty"`

	// GMSACredentialSpecName is the name of the GMSA credential spec to use.
	GmsaCredentialSpecName *string `json:"gmsaCredentialSpecName,omitempty" yaml:"gmsaCredentialSpecName,omitempty"`

	// HostProcess determines if a container should be run as a 'Host Process' container. All of a Pod's containers must have the same effective HostProcess value (it is not allowed to have a mix of HostProcess containers and non-HostProcess containers). In addition, if HostProcess is true then HostNetwork must also be set to true.
	HostProcess *bool `json:"hostProcess,omitempty" yaml:"hostProcess,omitempty"`

	// The UserName in Windows to run the entrypoint of the container process. Defaults to the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
	RunAsUserName *string `json:"runAsUserName,omitempty" yaml:"runAsUserName,omitempty"`
}

func NewWindowsSecurityContextOptions() *WindowsSecurityContextOptions {
	return &WindowsSecurityContextOptions{}
}

func NewWindowsSecurityContextOptionsWithSpec(spec *WindowsSecurityContextOptions) *WindowsSecurityContextOptions {
	
	return spec
}

func RegisterWindowsSecurityContextOptions(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[WindowsSecurityContextOptions]()).JsNamespace("k8s.core.v1").Fields(
		js.Field("GmsaCredentialSpec"),
		js.Field("GmsaCredentialSpecName"),
		js.Field("HostProcess"),
		js.Field("RunAsUserName"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewWindowsSecurityContextOptions)),
		js.Constructor(reflect.ValueOf(NewWindowsSecurityContextOptionsWithSpec)),
	)
}