// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewPriorityClass(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "v1")
	document.Set("kind", "PriorityClass")
	return document
}

func NewPriorityClassWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "v1")
	document.Set("kind", "PriorityClass")
	return document
}

func RegisterPriorityClass(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewPriorityClass)).JsModule("k8s/scheduling/v1").JsName("PriorityClass")
	jsRuntime.Constructor(reflect.ValueOf(NewPriorityClassWithSpec)).JsModule("k8s/scheduling/v1").JsName("PriorityClass")
	
	jsRuntime.Constructor(reflect.ValueOf(NewPriorityClass)).JsModule("k8s").JsName("PriorityClass")
	jsRuntime.Constructor(reflect.ValueOf(NewPriorityClassWithSpec)).JsModule("k8s").JsName("PriorityClass")
	
}