package main

type typeCustomization struct {
	Path                *string
	ExcludedFields      []string
	NativeType          *nativeTypeInfo
	GenerateAliasOnRoot bool
	IsDocument          bool
}

var typeCustomizations = map[string]typeCustomization{
	"admissionregistration/v1/AuditAnnotation":                      {},
	"admissionregistration/v1/MatchCondition":                       {},
	"admissionregistration/v1/MatchResources":                       {},
	"admissionregistration/v1/MutatingWebhook":                      {},
	"admissionregistration/v1/MutatingWebhookConfiguration":         {IsDocument: true, GenerateAliasOnRoot: true},
	"admissionregistration/v1/ParamKind":                            {},
	"admissionregistration/v1/RuleWithOperations":                   {},
	"admissionregistration/v1/ServiceReference":                     {},
	"admissionregistration/v1/ValidatingAdmissionPolicy":            {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"admissionregistration/v1/ValidatingAdmissionPolicyBinding":     {IsDocument: true, GenerateAliasOnRoot: true},
	"admissionregistration/v1/ValidatingAdmissionPolicyBindingSpec": {},
	"admissionregistration/v1/ValidatingAdmissionPolicySpec":        {},
	"admissionregistration/v1/ValidatingWebhook":                    {},
	"admissionregistration/v1/ValidatingWebhookConfiguration":       {IsDocument: true, GenerateAliasOnRoot: true},
	"admissionregistration/v1/Validation":                           {},
	"admissionregistration/v1/Variable":                             {},
	"admissionregistration/v1/WebhookClientConfig":                  {},
	"apiextensions/v1/CustomResourceDefinition":                     {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"apiregistration/v1/APIService":                                 {IsDocument: true, ExcludedFields: []string{"status"}},
	"apiregistration/v1/APIServiceSpec":                             {},
	"apps/v1/DaemonSet":                                             {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"apps/v1/DaemonSetSpec":                                         {},
	"apps/v1/DaemonSetUpdateStrategy":                               {},
	"apps/v1/Deployment":                                            {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"apps/v1/DeploymentSpec":                                        {},
	"apps/v1/DeploymentStrategy":                                    {},
	"apps/v1/ReplicaSet":                                            {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"apps/v1/ReplicaSetSpec":                                        {},
	"apps/v1/RollingUpdateDaemonSet":                                {},
	"apps/v1/RollingUpdateDeployment":                               {},
	"apps/v1/RollingUpdateStatefulSetStrategy":                      {},
	"apps/v1/StatefulSet":                                           {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"apps/v1/StatefulSetOrdinals":                                   {},
	"apps/v1/StatefulSetPersistentVolumeClaimRetentionPolicy":       {},
	"apps/v1/StatefulSetSpec":                                       {},
	"apps/v1/StatefulSetUpdateStrategy":                             {},
	"autoscaling/v2/ContainerResourceMetricSource":                  {},
	"autoscaling/v2/CrossVersionObjectReference":                    {},
	"autoscaling/v2/ExternalMetricSource":                           {},
	"autoscaling/v2/HorizontalPodAutoscaler":                        {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"autoscaling/v2/HorizontalPodAutoscalerBehavior":                {},
	"autoscaling/v2/HorizontalPodAutoscalerSpec":                    {},
	"autoscaling/v2/HPAScalingPolicy":                               {},
	"autoscaling/v2/HPAScalingRules":                                {},
	"autoscaling/v2/MetricIdentifier":                               {},
	"autoscaling/v2/MetricSpec":                                     {},
	"autoscaling/v2/MetricTarget":                                   {},
	"autoscaling/v2/ObjectMetricSource":                             {},
	"autoscaling/v2/PodsMetricSource":                               {},
	"autoscaling/v2/ResourceMetricSource":                           {},
	"batch/v1/CronJob":                                              {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"batch/v1/CronJobSpec":                                          {},
	"batch/v1/Job":                                                  {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"batch/v1/JobSpec":                                              {},
	"batch/v1/JobTemplateSpec":                                      {},
	"batch/v1/PodFailurePolicy":                                     {},
	"batch/v1/PodFailurePolicyOnExitCodesRequirement":               {},
	"batch/v1/PodFailurePolicyOnPodConditionsPattern":               {},
	"batch/v1/PodFailurePolicyRule":                                 {},
	"batch/v1/SuccessPolicy":                                        {},
	"batch/v1/SuccessPolicyRule":                                    {},
	"certificates/v1/CertificateSigningRequest":                     {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"certificates/v1/CertificateSigningRequestSpec":                 {},
	"coordination/v1/Lease":                                         {IsDocument: true},
	"coordination/v1/LeaseSpec":                                     {ExcludedFields: []string{"acquireTime", "renewTime"}},
	"certificates/v1alpha1/PodCertificateRequest":                   {IsDocument: true, ExcludedFields: []string{"status"}},
	"core/v1/Affinity":                                              {},
	"core/v1/AppArmorProfile":                                       {},
	"core/v1/Capabilities":                                          {},
	"core/v1/ClientIPConfig":                                        {},
	"core/v1/ClusterTrustBundleProjection":                          {},
	"core/v1/ConfigMap":                                             {IsDocument: true, GenerateAliasOnRoot: true},
	"core/v1/ConfigMapEnvSource":                                    {},
	"core/v1/ConfigMapKeySelector":                                  {},
	"core/v1/ConfigMapProjection":                                   {},
	"core/v1/ConfigMapVolumeSource":                                 {},
	"core/v1/Container":                                             {},
	"core/v1/ContainerPort":                                         {},
	"core/v1/ContainerResizePolicy":                                 {},
	"core/v1/ContainerRestartRule":                                  {},
	"core/v1/ContainerRestartRuleOnExitCodes":                       {},
	"core/v1/CSIPersistentVolumeSource":                             {},
	"core/v1/CSIVolumeSource":                                       {},
	"core/v1/DownwardAPIProjection":                                 {},
	"core/v1/DownwardAPIVolumeFile":                                 {},
	"core/v1/DownwardAPIVolumeSource":                               {},
	"core/v1/EmptyDirVolumeSource":                                  {},
	"core/v1/EndpointAddress":                                       {},
	"core/v1/EndpointPort":                                          {},
	"core/v1/Endpoints":                                             {IsDocument: true, GenerateAliasOnRoot: true},
	"core/v1/EndpointSubset":                                        {},
	"core/v1/EnvFromSource":                                         {},
	"core/v1/EnvVar":                                                {},
	"core/v1/EnvVarSource":                                          {},
	"core/v1/EphemeralVolumeSource":                                 {},
	"core/v1/ExecAction":                                            {},
	"core/v1/FCVolumeSource":                                        {},
	"core/v1/FileKeySelector":                                       {},
	"core/v1/GRPCAction":                                            {},
	"core/v1/HostAlias":                                             {},
	"core/v1/HostPathVolumeSource":                                  {},
	"core/v1/HTTPGetAction":                                         {},
	"core/v1/HTTPHeader":                                            {},
	"core/v1/ImageVolumeSource":                                     {},
	"core/v1/ISCSIPersistentVolumeSource":                           {},
	"core/v1/ISCSIVolumeSource":                                     {},
	"core/v1/KeyToPath":                                             {},
	"core/v1/Lifecycle":                                             {},
	"core/v1/LifecycleHandler":                                      {},
	"core/v1/LimitRange":                                            {IsDocument: true, GenerateAliasOnRoot: true},
	"core/v1/LimitRangeItem":                                        {},
	"core/v1/LimitRangeSpec":                                        {},
	"core/v1/LocalObjectReference":                                  {},
	"core/v1/LocalVolumeSource":                                     {},
	"core/v1/Namespace":                                             {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/NamespaceSpec":                                         {ExcludedFields: []string{"status"}},
	"core/v1/NFSVolumeSource":                                       {},
	"core/v1/NodeAffinity":                                          {},
	"core/v1/NodeSelector":                                          {},
	"core/v1/NodeSelectorRequirement":                               {},
	"core/v1/NodeSelectorTerm":                                      {},
	"core/v1/ObjectFieldSelector":                                   {},
	"core/v1/ObjectReference":                                       {},
	"core/v1/PersistentVolume":                                      {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/PersistentVolumeClaim":                                 {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/PersistentVolumeClaimSpec":                             {},
	"core/v1/PersistentVolumeClaimTemplate":                         {},
	"core/v1/PersistentVolumeClaimVolumeSource":                     {},
	"core/v1/PersistentVolumeSpec":                                  {ExcludedFields: []string{"awsElasticBlockStore", "azureDisk", "azureFile", "cephfs", "claimRef", "cinder", "flexVolume", "flocker", "gcePersistentDisk", "gitRepo", "glusterfs", "photonPersistentDisk", "portworxVolume", "quobyte", "rbd", "scaleIO", "storageos", "vsphereVolume"}},
	"core/v1/Pod":                                                   {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/PodAffinity":                                           {},
	"core/v1/PodAffinityTerm":                                       {},
	"core/v1/PodAntiAffinity":                                       {},
	"core/v1/PodCertificateProjection":                              {},
	"core/v1/PodDNSConfig":                                          {},
	"core/v1/PodDNSConfigOption":                                    {},
	"core/v1/PodOS":                                                 {ExcludedFields: []string{"ephemeralContainers", "overhead"}},
	"core/v1/PodReadinessGate":                                      {ExcludedFields: []string{"ephemeralContainers", "overhead"}},
	"core/v1/PodResourceClaim":                                      {ExcludedFields: []string{"ephemeralContainers", "overhead"}},
	"core/v1/PodSchedulingGate":                                     {ExcludedFields: []string{"ephemeralContainers", "overhead"}},
	"core/v1/PodSecurityContext":                                    {ExcludedFields: []string{"ephemeralContainers", "overhead"}},
	"core/v1/PodSpec":                                               {ExcludedFields: []string{"ephemeralContainers", "overhead"}},
	"core/v1/PodTemplateSpec":                                       {ExcludedFields: []string{"ephemeralContainers", "overhead"}},
	"core/v1/PreferredSchedulingTerm":                               {},
	"core/v1/Probe":                                                 {},
	"core/v1/ProjectedVolumeSource":                                 {},
	"core/v1/ReplicationController":                                 {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/ReplicationControllerSpec":                             {},
	"core/v1/ResourceClaim":                                         {},
	"core/v1/ResourceFieldSelector":                                 {},
	"core/v1/ResourceQuota":                                         {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/ResourceQuotaSpec":                                     {},
	"core/v1/ResourceRequirements":                                  {},
	"core/v1/ScopedResourceSelectorRequirement":                     {},
	"core/v1/ScopeSelector":                                         {},
	"core/v1/SeccompProfile":                                        {},
	"core/v1/Secret":                                                {IsDocument: true, GenerateAliasOnRoot: true},
	"core/v1/SecretEnvSource":                                       {},
	"core/v1/SecretKeySelector":                                     {},
	"core/v1/SecretProjection":                                      {},
	"core/v1/SecretReference":                                       {},
	"core/v1/SecretVolumeSource":                                    {},
	"core/v1/SecurityContext":                                       {},
	"core/v1/SELinuxOptions":                                        {},
	"core/v1/Service":                                               {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/ServiceAccount":                                        {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/ServicePort":                                           {ExcludedFields: []string{"status"}},
	"core/v1/ServiceSpec":                                           {ExcludedFields: []string{"status"}},
	"core/v1/ServiceAccountTokenProjection":                         {},
	"core/v1/SessionAffinityConfig":                                 {},
	"core/v1/SleepAction":                                           {},
	"core/v1/Sysctl":                                                {},
	"core/v1/TCPSocketAction":                                       {},
	"core/v1/Toleration":                                            {},
	"core/v1/TopologySelectorTerm":                                  {},
	"core/v1/TopologySelectorLabelRequirement":                      {},
	"core/v1/TopologySpreadConstraint":                              {},
	"core/v1/TypedLocalObjectReference":                             {},
	"core/v1/TypedObjectReference":                                  {},
	"core/v1/Volume":                                                {ExcludedFields: []string{"awsElasticBlockStore", "azureDisk", "azureFile", "cephfs", "cinder", "flexVolume", "flocker", "gcePersistentDisk", "gitRepo", "glusterfs", "photonPersistentDisk", "portworxVolume", "quobyte", "rbd", "scaleIO", "storageos", "vsphereVolume"}},
	"core/v1/VolumeDevice":                                          {},
	"core/v1/VolumeMount":                                           {},
	"core/v1/VolumeNodeAffinity":                                    {},
	"core/v1/VolumeProjection":                                      {},
	"core/v1/VolumeResourceRequirements":                            {},
	"core/v1/WeightedPodAffinityTerm":                               {},
	"core/v1/WindowsSecurityContextOptions":                         {},
	"discovery/v1/Endpoint":                                         {ExcludedFields: []string{"conditions", "deprecatedTopology"}},
	"discovery/v1/EndpointHints":                                    {},
	"discovery/v1/EndpointPort":                                     {},
	"discovery/v1/EndpointSlice":                                    {IsDocument: true, GenerateAliasOnRoot: true},
	"discovery/v1/ForNode":                                          {},
	"discovery/v1/ForZone":                                          {},
	"flowcontrol/v1/FlowSchema":                                     {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"flowcontrol/v1/FlowSchemaSpec":                                 {},
	"flowcontrol/v1/PriorityLevelConfiguration":                     {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"networking/v1/HTTPIngressPath":                                 {},
	"networking/v1/HTTPIngressRuleValue":                            {},
	"networking/v1/IPBlock":                                         {},
	"networking/v1/Ingress":                                         {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"networking/v1/IngressBackend":                                  {},
	"networking/v1/IngressClass":                                    {IsDocument: true, GenerateAliasOnRoot: true},
	"networking/v1/IngressClassParametersReference":                 {},
	"networking/v1/IngressClassSpec":                                {},
	"networking/v1/IngressRule":                                     {},
	"networking/v1/IngressServiceBackend":                           {},
	"networking/v1/IngressSpec":                                     {},
	"networking/v1/IngressTLS":                                      {},
	"networking/v1/NetworkPolicy":                                   {IsDocument: true, GenerateAliasOnRoot: true},
	"networking/v1/NetworkPolicyEgressRule":                         {},
	"networking/v1/NetworkPolicyIngressRule":                        {},
	"networking/v1/NetworkPolicyPeer":                               {},
	"networking/v1/NetworkPolicyPort":                               {},
	"networking/v1/NetworkPolicySpec":                               {},
	"networking/v1/ServiceBackendPort":                              {},
	"networking/v1/ServiceCIDR":                                     {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"node/v1/RuntimeClass":                                          {IsDocument: true, GenerateAliasOnRoot: true},
	"policy/v1/PodDisruptionBudget":                                 {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"policy/v1/PodDisruptionBudgetSpec":                             {},
	"rbac/v1/AggregationRule":                                       {},
	"rbac/v1/ClusterRole":                                           {IsDocument: true, GenerateAliasOnRoot: true},
	"rbac/v1/ClusterRoleBinding":                                    {IsDocument: true, GenerateAliasOnRoot: true},
	"rbac/v1/PolicyRule":                                            {},
	"rbac/v1/Role":                                                  {IsDocument: true, GenerateAliasOnRoot: true},
	"rbac/v1/RoleBinding":                                           {IsDocument: true, GenerateAliasOnRoot: true},
	"rbac/v1/RoleRef":                                               {},
	"rbac/v1/Subject":                                               {},
	"scheduling/v1/PriorityClass":                                   {IsDocument: true, GenerateAliasOnRoot: true},
	"storage/v1/CSIDriver":                                          {IsDocument: true},
	"storage/v1/CSIDriverSpec":                                      {},
	"storage/v1/CSIStorageCapacity":                                 {},
	"storage/v1/StorageClass":                                       {IsDocument: true, GenerateAliasOnRoot: true},
	"storage/v1/TokenRequest":                                       {},
	"storage/v1/VolumeAttributesClass":                              {IsDocument: true},
	"apimachinery/meta/v1/LabelSelector":                            {},
	"apimachinery/meta/v1/LabelSelectorRequirement":                 {},
	"apimachinery/meta/v1/ObjectMeta":                               {ExcludedFields: []string{"creationTimestamp", "deletionTimestamp", "deletionGracePeriodSeconds", "generation", "managedFields", "ownerReferences", "resourceVersion", "selfLink", "uid"}},
	"apimachinery/api/resource/Quantity":                            {NativeType: &nativeTypeInfo{Name: "number | string", IsPrimitive: true}},
	"apimachinery/util/intstr/IntOrString":                          {NativeType: &nativeTypeInfo{Name: "number | string", IsPrimitive: true}},
	"apiextensions/v1/JSON":                                         {NativeType: &nativeTypeInfo{Name: "Object", IsPrimitive: true}},
	"apiextensions/v1/JSONSchemaPropsOrArray":                       {NativeType: &nativeTypeInfo{Name: "JSONSchemaProps | JSONSchemaProps[]", IsPrimitive: true}},
	"apiextensions/v1/JSONSchemaPropsOrBool":                        {NativeType: &nativeTypeInfo{Name: "JSONSchemaProps | boolean", IsPrimitive: true}},
	"apiextensions/v1/JSONSchemaPropsOrStringArray":                 {NativeType: &nativeTypeInfo{Name: "JSONSchemaProps | string[]", IsPrimitive: true}},
}
