package main

type typeCustomization struct {
	Path                *string
	ExcludedFields      []string
	NativeType          *nativeTypeInfo
	GenerateAliasOnRoot bool
	IsDocument          bool
}

var typeCustomizations = map[string]typeCustomization{
	"admissionregistration/v1/MutatingWebhookConfiguration":     {IsDocument: true, GenerateAliasOnRoot: true},
	"admissionregistration/v1/ValidatingAdmissionPolicy":        {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"admissionregistration/v1/ValidatingAdmissionPolicyBinding": {IsDocument: true, GenerateAliasOnRoot: true},
	"admissionregistration/v1/ValidatingWebhookConfiguration":   {IsDocument: true, GenerateAliasOnRoot: true},
	"apiextensions/v1/CustomResourceDefinition":                 {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"apiregistration/v1/APIService":                             {IsDocument: true, ExcludedFields: []string{"status"}},
	"apps/v1/DaemonSet":                                         {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"apps/v1/Deployment":                                        {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"apps/v1/ReplicaSet":                                        {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"apps/v1/StatefulSet":                                       {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"autoscaling/v2/HorizontalPodAutoscaler":                    {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"batch/v1/CronJob":                                          {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"batch/v1/Job":                                              {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"certificates/v1/CertificateSigningRequest":                 {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"coordination/v1/Lease":                                     {IsDocument: true},
	"coordination/v1/LeaseSpec":                                 {ExcludedFields: []string{"acquireTime", "renewTime"}},
	"certificates/v1alpha1/PodCertificateRequest":               {IsDocument: true, ExcludedFields: []string{"status"}},
	"core/v1/ConfigMap":                                         {IsDocument: true, GenerateAliasOnRoot: true},
	"core/v1/Endpoints":                                         {IsDocument: true, GenerateAliasOnRoot: true},
	"core/v1/LimitRange":                                        {IsDocument: true, GenerateAliasOnRoot: true},
	"core/v1/Namespace":                                         {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/NamespaceSpec":                                     {ExcludedFields: []string{"status"}},
	"core/v1/PersistentVolume":                                  {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/PersistentVolumeClaim":                             {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/PersistentVolumeSpec":                              {ExcludedFields: []string{"awsElasticBlockStore", "azureDisk", "azureFile", "cephfs", "claimRef", "cinder", "flexVolume", "flocker", "gcePersistentDisk", "gitRepo", "glusterfs", "photonPersistentDisk", "portworxVolume", "quobyte", "rbd", "scaleIO", "storageos", "vsphereVolume"}},
	"core/v1/Pod":                                               {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/PodOS":                                             {ExcludedFields: []string{"ephemeralContainers", "overhead"}},
	"core/v1/PodReadinessGate":                                  {ExcludedFields: []string{"ephemeralContainers", "overhead"}},
	"core/v1/PodResourceClaim":                                  {ExcludedFields: []string{"ephemeralContainers", "overhead"}},
	"core/v1/PodSchedulingGate":                                 {ExcludedFields: []string{"ephemeralContainers", "overhead"}},
	"core/v1/PodSecurityContext":                                {ExcludedFields: []string{"ephemeralContainers", "overhead"}},
	"core/v1/PodSpec":                                           {ExcludedFields: []string{"ephemeralContainers", "overhead"}},
	"core/v1/PodTemplateSpec":                                   {ExcludedFields: []string{"ephemeralContainers", "overhead"}},
	"core/v1/ReplicationController":                             {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/ResourceQuota":                                     {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/ResourceRequirements":                              {ExcludedFields: []string{"claims"}},
	"core/v1/Secret":                                            {IsDocument: true, GenerateAliasOnRoot: true},
	"core/v1/Service":                                           {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/ServiceAccount":                                    {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"core/v1/ServicePort":                                       {ExcludedFields: []string{"status"}},
	"core/v1/ServiceSpec":                                       {ExcludedFields: []string{"status"}},
	"core/v1/Volume":                                            {ExcludedFields: []string{"awsElasticBlockStore", "azureDisk", "azureFile", "cephfs", "cinder", "flexVolume", "flocker", "gcePersistentDisk", "gitRepo", "glusterfs", "photonPersistentDisk", "portworxVolume", "quobyte", "rbd", "scaleIO", "storageos", "vsphereVolume"}},
	"discovery/v1/Endpoint":                                     {ExcludedFields: []string{"conditions", "deprecatedTopology"}},
	"discovery/v1/EndpointSlice":                                {IsDocument: true, GenerateAliasOnRoot: true},
	"flowcontrol/v1/FlowSchema":                                 {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"flowcontrol/v1/PriorityLevelConfiguration":                 {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"networking/v1/Ingress":                                     {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"networking/v1/IngressClass":                                {IsDocument: true, GenerateAliasOnRoot: true},
	"networking/v1/NetworkPolicy":                               {IsDocument: true, GenerateAliasOnRoot: true},
	"networking/v1/ServiceCIDR":                                 {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"node/v1/RuntimeClass":                                      {IsDocument: true, GenerateAliasOnRoot: true},
	"policy/v1/PodDisruptionBudget":                             {IsDocument: true, GenerateAliasOnRoot: true, ExcludedFields: []string{"status"}},
	"rbac/v1/ClusterRole":                                       {IsDocument: true, GenerateAliasOnRoot: true},
	"rbac/v1/ClusterRoleBinding":                                {IsDocument: true, GenerateAliasOnRoot: true},
	"rbac/v1/Role":                                              {IsDocument: true, GenerateAliasOnRoot: true},
	"rbac/v1/RoleBinding":                                       {IsDocument: true, GenerateAliasOnRoot: true},
	"scheduling/v1/PriorityClass":                               {IsDocument: true, GenerateAliasOnRoot: true},
	"storage/v1/CSIDriver":                                      {IsDocument: true},
	"storage/v1/StorageClass":                                   {IsDocument: true, GenerateAliasOnRoot: true},
	"storage/v1/VolumeAttributesClass":                          {IsDocument: true},
	"apimachinery/meta/v1/ObjectMeta":                           {ExcludedFields: []string{"creationTimestamp", "deletionTimestamp", "deletionGracePeriodSeconds", "generation", "managedFields", "ownerReferences", "resourceVersion", "selfLink", "uid"}},
	"apimachinery/api/resource/Quantity":                        {NativeType: &nativeTypeInfo{Name: "number | string", IsPrimitive: true}},
	"apimachinery/util/intstr/IntOrString":                      {NativeType: &nativeTypeInfo{Name: "number | string", IsPrimitive: true}},
	"apiextensions/v1/JSON":                                     {NativeType: &nativeTypeInfo{Name: "Object", IsPrimitive: true}},
	"apiextensions/v1/JSONSchemaPropsOrArray":                   {NativeType: &nativeTypeInfo{Name: "JSONSchemaProps | JSONSchemaProps[]", IsPrimitive: true}},
	"apiextensions/v1/JSONSchemaPropsOrBool":                    {NativeType: &nativeTypeInfo{Name: "JSONSchemaProps | boolean", IsPrimitive: true}},
	"apiextensions/v1/JSONSchemaPropsOrStringArray":             {NativeType: &nativeTypeInfo{Name: "JSONSchemaProps | string[]", IsPrimitive: true}},
}
