// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/grafana/sobek"
	"github.com/ohayocorp/anemos/pkg/core"
	"github.com/ohayocorp/anemos/pkg/js"
)

func NewCSIDriver(jsRuntime *js.JsRuntime) *core.Document {
	document := core.NewDocument(jsRuntime)
	document.Set("apiVersion", "v1")
	document.Set("kind", "CSIDriver")
	return document
}

func NewCSIDriverWithSpec(spec *sobek.Object) *core.Document {
	document := core.NewDocumentWithContent(spec)
	document.Set("apiVersion", "v1")
	document.Set("kind", "CSIDriver")
	return document
}

func RegisterCSIDriver(jsRuntime *js.JsRuntime) {
	jsRuntime.Constructor(reflect.ValueOf(NewCSIDriver)).JsNamespace("k8s.storage.v1").JsName("CSIDriver")
	jsRuntime.Constructor(reflect.ValueOf(NewCSIDriverWithSpec)).JsNamespace("k8s.storage.v1").JsName("CSIDriver")
	
}