// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// CSINodeSpec holds information about the specification of all CSI drivers installed on a node
type CSINodeSpec struct {
	// Drivers is a list of information of all CSI Drivers existing on a node. If all drivers in the list are uninstalled, this can become empty.
	Drivers []*CSINodeDriver `json:"drivers" yaml:"drivers"`
}

func NewCSINodeSpec() *CSINodeSpec {
	return &CSINodeSpec{}
}

func NewCSINodeSpecWithSpec(spec *CSINodeSpec) *CSINodeSpec {
	
	return spec
}

func RegisterCSINodeSpec(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[CSINodeSpec]()).JsNamespace("k8s.storage.v1").Fields(
		js.Field("Drivers"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewCSINodeSpec)),
		js.Constructor(reflect.ValueOf(NewCSINodeSpecWithSpec)),
	)
}