// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// TokenRequest contains parameters of a service account token.
type TokenRequest struct {
	// Audience is the intended audience of the token in "TokenRequestSpec". It will default to the audiences of kube apiserver.
	Audience string `json:"audience" yaml:"audience"`

	// ExpirationSeconds is the duration of validity of the token in "TokenRequestSpec". It has the same default value of "ExpirationSeconds" in "TokenRequestSpec".
	ExpirationSeconds *int `json:"expirationSeconds,omitempty" yaml:"expirationSeconds,omitempty"`
}

func NewTokenRequest() *TokenRequest {
	return &TokenRequest{}
}

func NewTokenRequestWithSpec(spec *TokenRequest) *TokenRequest {
	
	return spec
}

func RegisterTokenRequest(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[TokenRequest]()).JsNamespace("k8s.storage.v1").Fields(
		js.Field("Audience"),
		js.Field("ExpirationSeconds"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewTokenRequest)),
		js.Constructor(reflect.ValueOf(NewTokenRequestWithSpec)),
	)
}