// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// LeaseSpec is a specification of a Lease.
type LeaseSpec struct {
	// AcquireTime is a time when the current lease was acquired.
	AcquireTime *string `json:"acquireTime,omitempty" yaml:"acquireTime,omitempty"`

	// HolderIdentity contains the identity of the holder of a current lease. If Coordinated Leader Election is used, the holder identity must be equal to the elected LeaseCandidate.metadata.name field.
	HolderIdentity *string `json:"holderIdentity,omitempty" yaml:"holderIdentity,omitempty"`

	// LeaseDurationSeconds is a duration that candidates for a lease need to wait to force acquire it. This is measured against the time of last observed renewTime.
	LeaseDurationSeconds *int `json:"leaseDurationSeconds,omitempty" yaml:"leaseDurationSeconds,omitempty"`

	// LeaseTransitions is the number of transitions of a lease between holders.
	LeaseTransitions *int `json:"leaseTransitions,omitempty" yaml:"leaseTransitions,omitempty"`

	// PreferredHolder signals to a lease holder that the lease has a more optimal holder and should be given up. This field can only be set if Strategy is also set.
	PreferredHolder *string `json:"preferredHolder,omitempty" yaml:"preferredHolder,omitempty"`

	// RenewTime is a time when the current holder of a lease has last updated the lease.
	RenewTime *string `json:"renewTime,omitempty" yaml:"renewTime,omitempty"`

	// Strategy indicates the strategy for picking the leader for coordinated leader election. If the field is not specified, there is no active coordination for this lease. (Alpha) Using this field requires the CoordinatedLeaderElection feature gate to be enabled.
	Strategy *string `json:"strategy,omitempty" yaml:"strategy,omitempty"`
}

func NewLeaseSpec() *LeaseSpec {
	return &LeaseSpec{}
}

func NewLeaseSpecWithSpec(spec *LeaseSpec) *LeaseSpec {
	
	return spec
}

func RegisterLeaseSpec(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[LeaseSpec]()).JsNamespace("k8s.coordination.v1").Fields(
		js.Field("AcquireTime"),
		js.Field("HolderIdentity"),
		js.Field("LeaseDurationSeconds"),
		js.Field("LeaseTransitions"),
		js.Field("PreferredHolder"),
		js.Field("RenewTime"),
		js.Field("Strategy"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewLeaseSpec)),
		js.Constructor(reflect.ValueOf(NewLeaseSpecWithSpec)),
	)
}