// Code generated by types_generator.go; DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// The names of the group, the version, and the resource.
type GroupVersionResource struct {
	// The name of the group.
	Group *string `json:"group,omitempty" yaml:"group,omitempty"`

	// The name of the resource.
	Resource *string `json:"resource,omitempty" yaml:"resource,omitempty"`

	// The name of the version.
	Version *string `json:"version,omitempty" yaml:"version,omitempty"`
}

func NewGroupVersionResource() *GroupVersionResource {
	return &GroupVersionResource{}
}

func NewGroupVersionResourceWithSpec(spec *GroupVersionResource) *GroupVersionResource {
	
	return spec
}

func RegisterGroupVersionResource(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[GroupVersionResource]()).JsNamespace("k8s.storagemigration.v1alpha1").Fields(
		js.Field("Group"),
		js.Field("Resource"),
		js.Field("Version"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewGroupVersionResource)),
		js.Constructor(reflect.ValueOf(NewGroupVersionResourceWithSpec)),
	)
}