// Code generated by types_generator.go; DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// Describes the state of a migration at a certain point.
type MigrationCondition struct {
	// The last time this condition was updated.
	LastUpdateTime *string `json:"lastUpdateTime,omitempty" yaml:"lastUpdateTime,omitempty"`

	// A human readable message indicating details about the transition.
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`

	// The reason for the condition's last transition.
	Reason *string `json:"reason,omitempty" yaml:"reason,omitempty"`

	// Status of the condition, one of True, False, Unknown.
	Status string `json:"status" yaml:"status"`

	// Type of the condition.
	Type string `json:"type" yaml:"type"`
}

func NewMigrationCondition() *MigrationCondition {
	return &MigrationCondition{}
}

func NewMigrationConditionWithSpec(spec *MigrationCondition) *MigrationCondition {
	
	return spec
}

func RegisterMigrationCondition(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[MigrationCondition]()).JsNamespace("k8s.storagemigration.v1alpha1").Fields(
		js.Field("LastUpdateTime"),
		js.Field("Message"),
		js.Field("Reason"),
		js.Field("Status"),
		js.Field("Type"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewMigrationCondition)),
		js.Constructor(reflect.ValueOf(NewMigrationConditionWithSpec)),
	)
}