// Code generated by types_generator.go; DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// Spec of the storage version migration.
type StorageVersionMigrationSpec struct {
	// The token used in the list options to get the next chunk of objects to migrate. When the .status.conditions indicates the migration is "Running", users can use this token to check the progress of the migration.
	ContinueToken *string `json:"continueToken,omitempty" yaml:"continueToken,omitempty"`

	// The resource that is being migrated. The migrator sends requests to the endpoint serving the resource. Immutable.
	Resource *GroupVersionResource `json:"resource" yaml:"resource"`
}

func NewStorageVersionMigrationSpec() *StorageVersionMigrationSpec {
	return &StorageVersionMigrationSpec{}
}

func NewStorageVersionMigrationSpecWithSpec(spec *StorageVersionMigrationSpec) *StorageVersionMigrationSpec {
	
	return spec
}

func RegisterStorageVersionMigrationSpec(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[StorageVersionMigrationSpec]()).JsNamespace("k8s.storagemigration.v1alpha1").Fields(
		js.Field("ContinueToken"),
		js.Field("Resource"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewStorageVersionMigrationSpec)),
		js.Constructor(reflect.ValueOf(NewStorageVersionMigrationSpecWithSpec)),
	)
}