// Code generated by types_generator.go; DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
)

// StorageVersionMigration represents a migration of stored data to the latest storage version.
type StorageVersionMigration struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty" yaml:"apiVersion,omitempty"`

	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`

	// Standard object metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *apimachinerymetav1.ObjectMeta `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	// Specification of the migration.
	Spec *StorageVersionMigrationSpec `json:"spec,omitempty" yaml:"spec,omitempty"`
}

func NewStorageVersionMigration() *StorageVersionMigration {
	return &StorageVersionMigration{}
}

func NewStorageVersionMigrationWithSpec(spec *StorageVersionMigration) *StorageVersionMigration {
	version := "v1alpha1"
	kind := "StorageVersionMigration"
	
	spec.ApiVersion = &version
	spec.Kind = &kind
	return spec
}

func RegisterStorageVersionMigration(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[StorageVersionMigration]()).JsNamespace("k8s.storagemigration.v1alpha1").Fields(
		js.Field("ApiVersion"),
		js.Field("Kind"),
		js.Field("Metadata"),
		js.Field("Spec"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewStorageVersionMigration)),
		js.Constructor(reflect.ValueOf(NewStorageVersionMigrationWithSpec)),
	)
}