// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// BoundObjectReference is a reference to an object that a token is bound to.
type BoundObjectReference struct {
	// API version of the referent.
	ApiVersion *string `json:"apiVersion,omitempty" yaml:"apiVersion,omitempty"`

	// Kind of the referent. Valid kinds are 'Pod' and 'Secret'.
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`

	// Name of the referent.
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`

	// UID of the referent.
	Uid *string `json:"uid,omitempty" yaml:"uid,omitempty"`
}

func NewBoundObjectReference() *BoundObjectReference {
	return &BoundObjectReference{}
}

func NewBoundObjectReferenceWithSpec(spec *BoundObjectReference) *BoundObjectReference {
	
	return spec
}

func RegisterBoundObjectReference(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[BoundObjectReference]()).JsNamespace("k8s.authentication.v1").Fields(
		js.Field("ApiVersion"),
		js.Field("Kind"),
		js.Field("Name"),
		js.Field("Uid"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewBoundObjectReference)),
		js.Constructor(reflect.ValueOf(NewBoundObjectReferenceWithSpec)),
	)
}