// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	apimachinerymetav1 "github.com/ohayocorp/anemos/pkg/k8s/apimachinery/meta/v1"
)

// SelfSubjectReview contains the user information that the kube-apiserver has about the user making this request. When using impersonation, users will receive the user info of the user being impersonated.  If impersonation or request header authentication is used, any extra keys will have their case ignored and returned as lowercase.
type SelfSubjectReview struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty" yaml:"apiVersion,omitempty"`

	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`

	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *apimachinerymetav1.ObjectMeta `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	// Status is filled in by the server with the user attributes.
	Status *SelfSubjectReviewStatus `json:"status,omitempty" yaml:"status,omitempty"`
}

func NewSelfSubjectReview() *SelfSubjectReview {
	return &SelfSubjectReview{}
}

func NewSelfSubjectReviewWithSpec(spec *SelfSubjectReview) *SelfSubjectReview {
	version := "v1"
	kind := "SelfSubjectReview"
	
	spec.ApiVersion = &version
	spec.Kind = &kind
	return spec
}

func RegisterSelfSubjectReview(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[SelfSubjectReview]()).JsNamespace("k8s.authentication.v1").Fields(
		js.Field("ApiVersion"),
		js.Field("Kind"),
		js.Field("Metadata"),
		js.Field("Status"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewSelfSubjectReview)),
		js.Constructor(reflect.ValueOf(NewSelfSubjectReviewWithSpec)),
	)
}