// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// TokenReviewStatus is the result of the token authentication request.
type TokenReviewStatus struct {
	// Audiences are audience identifiers chosen by the authenticator that are compatible with both the TokenReview and token. An identifier is any identifier in the intersection of the TokenReviewSpec audiences and the token's audiences. A client of the TokenReview API that sets the spec.audiences field should validate that a compatible audience identifier is returned in the status.audiences field to ensure that the TokenReview server is audience aware. If a TokenReview returns an empty status.audience field where status.authenticated is "true", the token is valid against the audience of the Kubernetes API server.
	Audiences *[]string `json:"audiences,omitempty" yaml:"audiences,omitempty"`

	// Authenticated indicates that the token was associated with a known user.
	Authenticated *bool `json:"authenticated,omitempty" yaml:"authenticated,omitempty"`

	// Error indicates that the token couldn't be checked
	Error *string `json:"error,omitempty" yaml:"error,omitempty"`

	// User is the UserInfo associated with the provided token.
	User *UserInfo `json:"user,omitempty" yaml:"user,omitempty"`
}

func NewTokenReviewStatus() *TokenReviewStatus {
	return &TokenReviewStatus{}
}

func NewTokenReviewStatusWithSpec(spec *TokenReviewStatus) *TokenReviewStatus {
	
	return spec
}

func RegisterTokenReviewStatus(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[TokenReviewStatus]()).JsNamespace("k8s.authentication.v1").Fields(
		js.Field("Audiences"),
		js.Field("Authenticated"),
		js.Field("Error"),
		js.Field("User"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewTokenReviewStatus)),
		js.Constructor(reflect.ValueOf(NewTokenReviewStatusWithSpec)),
	)
}