// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// CapacityRequirements defines the capacity requirements for a specific device request.
type CapacityRequirements struct {
	// Requests represent individual device resource requests for distinct resources, all of which must be provided by the device.
	// This value is used as an additional filtering condition against the available capacity on the device. This is semantically equivalent to a CEL selector with `device.capacity[<domain>].<name>.compareTo(quantity(<request quantity>)) >= 0`. For example, device.capacity['test-driver.cdi.k8s.io'].counters.compareTo(quantity('2')) >= 0.
	// When a requestPolicy is defined, the requested amount is adjusted upward to the nearest valid value based on the policy. If the requested amount cannot be adjusted to a valid value—because it exceeds what the requestPolicy allows— the device is considered ineligible for allocation.
	// For any capacity that is not explicitly requested: - If no requestPolicy is set, the default consumed capacity is equal to the full device capacity
	//   (i.e., the whole device is claimed).
	// - If a requestPolicy is set, the default consumed capacity is determined according to that policy.
	// If the device allows multiple allocation, the aggregated amount across all requests must not exceed the capacity value. The consumed capacity, which may be adjusted based on the requestPolicy if defined, is recorded in the resource claim’s status.devices[*].consumedCapacity field.
	Requests *any `json:"requests,omitempty" yaml:"requests,omitempty"`
}

func NewCapacityRequirements() *CapacityRequirements {
	return &CapacityRequirements{}
}

func NewCapacityRequirementsWithSpec(spec *CapacityRequirements) *CapacityRequirements {
	
	return spec
}

func RegisterCapacityRequirements(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[CapacityRequirements]()).JsNamespace("k8s.resource.v1").Fields(
		js.Field("Requests"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewCapacityRequirements)),
		js.Constructor(reflect.ValueOf(NewCapacityRequirementsWithSpec)),
	)
}