// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// DeviceRequestAllocationResult contains the allocation result for one request.
type DeviceRequestAllocationResult struct {
	// AdminAccess indicates that this device was allocated for administrative access. See the corresponding request field for a definition of mode.
	// This is an alpha field and requires enabling the DRAAdminAccess feature gate. Admin access is disabled if this field is unset or set to false, otherwise it is enabled.
	AdminAccess *bool `json:"adminAccess,omitempty" yaml:"adminAccess,omitempty"`

	// BindingConditions contains a copy of the BindingConditions from the corresponding ResourceSlice at the time of allocation.
	// This is an alpha field and requires enabling the DRADeviceBindingConditions and DRAResourceClaimDeviceStatus feature gates.
	BindingConditions *[]string `json:"bindingConditions,omitempty" yaml:"bindingConditions,omitempty"`

	// BindingFailureConditions contains a copy of the BindingFailureConditions from the corresponding ResourceSlice at the time of allocation.
	// This is an alpha field and requires enabling the DRADeviceBindingConditions and DRAResourceClaimDeviceStatus feature gates.
	BindingFailureConditions *[]string `json:"bindingFailureConditions,omitempty" yaml:"bindingFailureConditions,omitempty"`

	// ConsumedCapacity tracks the amount of capacity consumed per device as part of the claim request. The consumed amount may differ from the requested amount: it is rounded up to the nearest valid value based on the device’s requestPolicy if applicable (i.e., may not be less than the requested amount).
	// The total consumed capacity for each device must not exceed the DeviceCapacity's Value.
	// This field is populated only for devices that allow multiple allocations. All capacity entries are included, even if the consumed amount is zero.
	ConsumedCapacity map[string]any `json:"consumedCapacity,omitempty" yaml:"consumedCapacity,omitempty"`

	// Device references one device instance via its name in the driver's resource pool. It must be a DNS label.
	Device string `json:"device" yaml:"device"`

	// Driver specifies the name of the DRA driver whose kubelet plugin should be invoked to process the allocation once the claim is needed on a node.
	// Must be a DNS subdomain and should end with a DNS domain owned by the vendor of the driver.
	Driver string `json:"driver" yaml:"driver"`

	// This name together with the driver name and the device name field identify which device was allocated (`<driver name>/<pool name>/<device name>`).
	// Must not be longer than 253 characters and may contain one or more DNS sub-domains separated by slashes.
	Pool string `json:"pool" yaml:"pool"`

	// Request is the name of the request in the claim which caused this device to be allocated. If it references a subrequest in the firstAvailable list on a DeviceRequest, this field must include both the name of the main request and the subrequest using the format <main request>/<subrequest>.
	// Multiple devices may have been allocated per request.
	Request string `json:"request" yaml:"request"`

	// ShareID uniquely identifies an individual allocation share of the device, used when the device supports multiple simultaneous allocations. It serves as an additional map key to differentiate concurrent shares of the same device.
	ShareID *string `json:"shareID,omitempty" yaml:"shareID,omitempty"`

	// A copy of all tolerations specified in the request at the time when the device got allocated.
	// The maximum number of tolerations is 16.
	// This is an alpha field and requires enabling the DRADeviceTaints feature gate.
	Tolerations []*DeviceToleration `json:"tolerations,omitempty" yaml:"tolerations,omitempty"`
}

func NewDeviceRequestAllocationResult() *DeviceRequestAllocationResult {
	return &DeviceRequestAllocationResult{}
}

func NewDeviceRequestAllocationResultWithSpec(spec *DeviceRequestAllocationResult) *DeviceRequestAllocationResult {
	
	return spec
}

func RegisterDeviceRequestAllocationResult(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[DeviceRequestAllocationResult]()).JsNamespace("k8s.resource.v1").Fields(
		js.Field("AdminAccess"),
		js.Field("BindingConditions"),
		js.Field("BindingFailureConditions"),
		js.Field("ConsumedCapacity"),
		js.Field("Device"),
		js.Field("Driver"),
		js.Field("Pool"),
		js.Field("Request"),
		js.Field("ShareID"),
		js.Field("Tolerations"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewDeviceRequestAllocationResult)),
		js.Constructor(reflect.ValueOf(NewDeviceRequestAllocationResultWithSpec)),
	)
}