// Code generated by types_generator.go; DO NOT EDIT.

package v1

import (
	"reflect"

	"github.com/ohayocorp/anemos/pkg/js"

	
)

// ResourcePool describes the pool that ResourceSlices belong to.
type ResourcePool struct {
	// Generation tracks the change in a pool over time. Whenever a driver changes something about one or more of the resources in a pool, it must change the generation in all ResourceSlices which are part of that pool. Consumers of ResourceSlices should only consider resources from the pool with the highest generation number. The generation may be reset by drivers, which should be fine for consumers, assuming that all ResourceSlices in a pool are updated to match or deleted.
	// Combined with ResourceSliceCount, this mechanism enables consumers to detect pools which are comprised of multiple ResourceSlices and are in an incomplete state.
	Generation int `json:"generation" yaml:"generation"`

	// Name is used to identify the pool. For node-local devices, this is often the node name, but this is not required.
	// It must not be longer than 253 characters and must consist of one or more DNS sub-domains separated by slashes. This field is immutable.
	Name string `json:"name" yaml:"name"`

	// ResourceSliceCount is the total number of ResourceSlices in the pool at this generation number. Must be greater than zero.
	// Consumers can use this to check whether they have seen all ResourceSlices belonging to the same pool.
	ResourceSliceCount int `json:"resourceSliceCount" yaml:"resourceSliceCount"`
}

func NewResourcePool() *ResourcePool {
	return &ResourcePool{}
}

func NewResourcePoolWithSpec(spec *ResourcePool) *ResourcePool {
	
	return spec
}

func RegisterResourcePool(jsRuntime *js.JsRuntime) {
	jsRuntime.Type(reflect.TypeFor[ResourcePool]()).JsNamespace("k8s.resource.v1").Fields(
		js.Field("Generation"),
		js.Field("Name"),
		js.Field("ResourceSliceCount"),
	).Constructors(
		js.Constructor(reflect.ValueOf(NewResourcePool)),
		js.Constructor(reflect.ValueOf(NewResourcePoolWithSpec)),
	)
}